import { useState, useMemo } from 'react';
import { Search, ChevronDown, ChevronUp, Package, Tag, MapPin } from 'lucide-react';
import { Input } from '@/components/ui/input';

const BRANDS = [
  // FASHION & LUXURY
  { id: 1, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Bottega Veneta', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Intrecciato woven leather, bags, shoes, minimalist luxury', products: 'BAGS: Cassette Bag Padded Intrecciato, Cassette Bag Small, Cassette Bag Crossbody, Jodie Mini Intrecciato, Jodie Small, Jodie Teen, Pouch Clutch Large, Pouch Clutch Small, Pouch On Strap, Padded Cassette Crossbody, Andiamo Medium, Andiamo Small, Andiamo Clutch, Sardine Small, Sardine Mini, Intrecciato Small Shoulder, Arco Tote Medium, Arco Tote Small, Arco Camera Bag, Hop Small Bag, Kalimero 16, Cabat Intrecciato Tote, Brick Cassette, Loop Crossbody, Point Clutch, Nodini Crossbody\nSLG: Intrecciato Card Case, Intrecciato Zip Around Wallet, Intrecciato Bifold Wallet, Intrecciato Coin Purse, Intrecciato Key Case, Intrecciato Phone Pouch, Cassette Card Holder, Loop Card Case, Triangle Zip Case\nSHOES: Lido Sandal Flat, Lido Sandal 90mm, Puddle Boot Short, Puddle Boot Tall, Tire Chelsea Boot, Tire Ankle Boot, Orbit Sneaker, Vulcan Sneaker, Salon 01 Pump, Stretch Sandal 90mm, BV Bold Sandal, Flash Mule, Dot Sock Pump, Quilted Padded Boot, Lug Chelsea Boot\nBELTS: Intrecciato Belt 3cm, Intrecciato Belt 2cm, Triangle Buckle Belt, Cassette Belt\nACCESSORIES: Intrecciato Silk Scarf, Triangle Sunglasses, Angle Sunglasses, BV Classic Sunglasses, Intrecciato Beanie, Intrecciato Gloves, Intrecciato Tie, Leather Coat, Cashmere Oversized Sweater, Compact Cotton Shirt, Wide-Leg Trouser, BV Embossed Tee, Leather Blouson, Stretch Dress, Knit Polo' },
  { id: 2, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Brunello Cucinelli', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Cashmere, quiet luxury, Italian craftsmanship', products: 'WOMEN: Cashmere V-Neck Sweater, Cashmere Crewneck Sweater, Cashmere Cardigan Button-Front, Cashmere Cardigan Open-Front, Cashmere Turtleneck, Cashmere Hoodie, Cashmere Jogger Pant, Cashmere Track Suit Set, Cashmere Poncho, Cashmere Cape, Cashmere Blanket Scarf, Silk-Cashmere Tee, Cotton Jersey Tee, Linen Shirt, Cotton Poplin Shirt, Silk Blouse, Leather Belt Monili, Monili Chain Bag, Monili Crossbody, Suede Weekend Bag, Suede Clutch, Suede Loafer, Suede Sneaker, Suede Ankle Boot, Cashmere Coat, Shearling Jacket, Linen Blazer, Cotton Trouser, Denim Five-Pocket, Pleated Skirt, Knit Dress, Cashmere Beanie, Cashmere Gloves\nMEN: Cashmere V-Neck Sweater, Cashmere Crewneck, Cashmere Zip Cardigan, Cashmere Half-Zip, Cashmere Polo, Cashmere Hoodie, Cashmere Jogger, Cotton Jersey Polo, Linen Shirt, Cotton Oxford, Suede Bomber Jacket, Suede Field Jacket, Cashmere Blazer, Linen Blazer, Cotton Suit, Linen Trouser, Denim Five-Pocket, Bermuda Short, Cotton Tee, Suede Sneaker, Suede Loafer, Suede Chelsea Boot, Suede Belt, Leather Weekender, Leather Backpack, Cashmere Scarf, Cashmere Beanie\nHOME: Cashmere Throw Blanket, Cashmere Pillow, Leather Tray, Leather Box' },
  { id: 3, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Canada Goose', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Premium arctic parkas, down jackets, knitwear', products: 'PARKAS: Expedition Parka, Expedition Parka Heritage, Langford Parka, Langford Parka Black Label, Wyndham Parka, Carson Parka, Chateau Parka, Rossclair Parka, Shelburne Parka, Lorette Parka, Trillium Parka, Mystique Parka, Kensington Parka\nJACKETS: Chilliwack Bomber, Chilliwack Bomber Heritage, Freestyle Crew Vest, Freestyle Vest, HyBridge Lite Jacket, HyBridge Down Jacket, Cypress Jacket, Crofton Hoody, Crofton Puffer, Lodge Hoody, Lodge Down Jacket, Armstrong Hoody, Everett Bomber, Nanaimo Jacket Raincoat\nKNITWEAR: Merino Wool Beanie, Merino Wool Scarf, Arctic Disc Toque Beanie, Logo Rib Toque, Merino Wool Gloves\nACCESSORIES: Snow Mantra Mitt, Arctic Down Glove, Logo Belt, Northern Lights Backpack, Small Item Bag\nBLACK LABEL: Clair Parka, Trenton Jacket, Patterson Coat, Carson Jacket, Hybridge Knit, Pastel Collection' },
  { id: 4, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Chanel', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Haute couture, RTW, bags, shoes, eyewear', products: 'WOMEN BAGS: Classic Flap Small Lambskin, Classic Flap Small Caviar, Classic Flap Medium Lambskin, Classic Flap Medium Caviar, Classic Flap Jumbo Caviar, Classic Flap Maxi Lambskin, Classic Flap Mini Square, Classic Flap Mini Rectangular, Boy Bag Small Caviar, Boy Bag Medium Caviar, Boy Bag Old Medium, Chanel 19 Small, Chanel 19 Large, Chanel 19 Maxi, WOC Caviar, WOC Lambskin, Gabrielle Hobo Small, Gabrielle Hobo Medium, Gabrielle Backpack, Deauville Tote Large Canvas, Deauville Tote Medium, Chanel 22 Small, Chanel 22 Medium, Chanel 22 Large, Coco Handle Small, Coco Handle Medium, Business Affinity Medium, Business Affinity Large, Mini Flap with Top Handle, Mini Flap Vanity, Vanity Case Small, Vanity Case Medium, Pearl Crush Mini Flap, Pearl Crush Small Flap, 2.55 Reissue 225, 2.55 Reissue 226, 2.55 Reissue 227, Grand Shopping Tote, Trendy CC Small, Classic Camera Case, Backpack in Seoul, Chain Around Flap\nSMALL LEATHER GOODS: Long Flap Wallet Caviar, Long Flap Wallet Lambskin, Small Flap Wallet Caviar, Compact Wallet, Zipped Card Holder Caviar, Classic Card Holder Caviar, Card Holder Grained, Coin Purse Caviar, Zip-Around Wallet, O-Case Pouch Caviar, Clutch with Chain, Phone Case Caviar, Classic Pouch, Camélia Card Case, Make-Up Case Vanity\nSHOES: Slingback Pump Two-Tone 6.5cm, Slingback Pump 8.5cm, CC Espadrilles Lambskin, CC Espadrilles Tweed, Ballet Flats CC Cap Toe, CC Logo Sneaker Suede Calfskin, CC Logo Sneaker Fabric, Mules CC Cap Toe, Interlocking CC Sandal, Ankle Boots CC Short, Ankle Boots CC Lace-Up, Thong Sandal CC Logo, Loafers CC Turnlock, Combat Boot CC Chain, Dad Sandal CC, Wedge Espadrille CC\nRTW: Classic Tweed Jacket, Little Black Dress, Knit Cardigan CC Buttons, Silk Blouse Print, Pleated Midi Skirt, Tweed Coat Long, Cashmere Twinset, Logo Tee CC, Denim Jacket CC, Leather Jacket CC, Tweed Shorts, Knit Dress CC' },
  { id: 5, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Dior', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Couture, RTW, bags, shoes, Baby Dior', products: 'WOMEN BAGS: Lady Dior Medium Cannage, Lady Dior Small Cannage, Lady Dior Mini Cannage, Lady Dior My ABCDior Medium, Lady Dior My ABCDior Small, Lady Dior Micro, Lady D-Joy Medium, Lady D-Joy Small, Lady D-Lite Medium, Lady D-Lite Mini, Book Tote Oblique Large, Book Tote Oblique Medium, Book Tote Oblique Small, Saddle Bag Oblique Jacquard, Saddle Bag Grained Calfskin, 30 Montaigne Bag Oblique, 30 Montaigne Avenue, 30 Montaigne Chain, Dior Bobby East-West Medium, Dior Bobby Small, Dior Caro Medium Cannage, Dior Caro Small, Miss Dior Top Handle Bag, Miss Dior Mini, Dior Toujours Medium, Dior Toujours Small, DiorTravel Vanity, DiorTravel Backpack\nMEN BAGS: Dior Saddle Messenger Oblique, Dior Rider Backpack Oblique, Dior 8 Backpack, CD Diamond Crossbody, Roller Messenger Oblique, Hit the Road Backpack\nSHOES WOMEN: J\'Adior Slingback Pump 6.5cm, J\'Adior Slingback Pump 10cm, Dior Walk\'n\'Dior Sneaker Canvas, Dior Walk\'n\'Dior Sneaker Oblique, Dior-ID Sneaker White, D-Joy Pump 6.5cm, D-Joy Pump 10cm, Dway Slide Oblique, Dioract Sandal, D-Dior Boot, Dior Granville Loafer, CD Loafer Oblique\nSHOES MEN: B30 Sneaker, B27 Sneaker High, B27 Sneaker Low, B22 Sneaker, B23 Sneaker Oblique, Dior Explorer Boot, Dior Evidence Loafer, CD Diamond Derby\nRTW: Bar Jacket, J\'Adior 8 Cashmere Sweater, Toile de Jouy Dress, CD Embroidered Tee, Dior Oblique Hoodie, Dior Oblique Jacket, Tulle Midi Skirt, CD Diamond Knit, Saddle Denim Jacket' },
  { id: 6, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Dolce & Gabbana', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Italian luxury, prints, suits, dresses, eyewear', products: 'BAGS: Sicily Bag Medium, Sicily Bag Small, Sicily Bag Mini, Sicily Soft, Devotion Shoulder Bag Medium, Devotion Shoulder Small, DG Girls Crossbody, DG Logo Tote, DG Logo Shopping Bag, Miss Sicily Medium, Patchwork Bag, Phone Bag DG Logo, Crespo Tote\nSHOES: Portofino Sneaker Classic White, Portofino Sneaker Printed, NS1 Sneaker, Daymaster Sneaker, Crystal Embellished Pump, Crystal T-Strap Sandal, Keira Platform, Bianca Pump, Devotion Flat, Brocade Slipper, Chelsea Boot DG, Combat Boot, DG Logo Slide\nEYEWEAR: DG Amore Sunglasses, DG Logo Cat Eye, DG Baroque Sunglasses, DG Shield, DG Aviator, DG Optical Round\nACCESSORIES: DG Logo Belt, DG Crown Belt Buckle, Silk Scarf Printed, Majolica Print Scarf, DG Logo Cap, DG Logo Beanie, DG Logo Tie, DG Logo Pocket Square\nRTW: Tuxedo Suit Martini Fit, Sicilia Fit Suit, Printed Silk Shirt Majolica, Crown Print Tee, DG Logo Tee, DG Logo Hoodie, Lace Midi Dress, Brocade Shift Dress, Corset Top, Tulle Skirt, Leopard Print Dress, Floral Midi Dress, DG Logo Sweatshirt, Brocade Blazer, Cashmere Cardigan' },
  { id: 7, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Fendi', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Baguette bags, fur, RTW, shoes, accessories, kids', products: 'BAGS: Baguette FF Jacquard Medium, Baguette Nappa Leather, Baguette Sequin, Baguette Chain Midi, Baguette Phone Pouch, Peekaboo ISeeU Medium, Peekaboo ISeeU Mini, Peekaboo ISeeU Petite, Fendi First Small, Fendi First Medium, Fendi First Sight, Sunshine Shopper Medium, Sunshine Shopper Mini, By The Way Mini, By The Way Medium, Fendigraphy Small, Fendigraphy Medium, Fendi O\'Lock Swing, Mon Trésor Mini Bucket, Fendi Way Small, Kan I Small, Kan I F, Baguette Soft Trunk\nSHOES: Fendi Match High Top, Fendi Match Low Top, Fendi Flow Runner, Fendi Step Sneaker, Fendi Faster Sneaker, Baguette Slide FF, FF Slide, Fendi First Pump 95mm, Fendi First Sandal, Karligraphy Slingback, FF Cowboy Boot, Baguette Boot\nBELTS: FF Logo Belt 40mm, FF Logo Belt Reversible, Fendi O\'Lock Belt Slim, Fendi Fendigraphy Belt\nEYEWEAR: FF Sunglasses Square, Fendi First Shield, Fendi O\'Lock Round, Fendi Way Cat Eye, Baguette Sunglasses, FF Optical Frame\nACCESSORIES: FF Logo Scarf Silk, FF Wool Scarf, FF Logo Beanie, FF Logo Cap, FF Logo Tie, FF Logo Tee, Fendi Roma Hoodie, FF Monogram Jacket, Leather Biker Jacket, FF Denim, FF Monogram Swim, Tailored Trousers, Silk Print Shirt, FF Poncho, FF Ski Suit' },
  { id: 8, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Gentle Monster', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Premium designer eyewear, artistic retail', products: 'SUNGLASSES: Maison series (various), Her 01, Her T1, Dreamer Hoff, Dreamer 17, MM006, MM010, Palette, Mambo, My Ma, Rick, Tam, Tomy, Conic, Rosy, South Side, East Moon, Eve, Lilit, Solo, Modmo, Dummy, Bowie, Absente, In Scarlet, Jennie, Flatba\nOPTICAL: Lo Cell, South Side Optical, Her Optical, Conic Optical, Rick Optical, Tam Optical, Modmo Optical, Dreamer Optical\nCOLLABORATIONS: Gentle Monster x Jennie (various), Gentle Monster x Tamburins, Gentle Monster x Maison Margiela\nACCESSORIES: Leather Case, Hard Case, Cleaning Cloth, Chain Strap\nTAMBURINS (by Gentle Monster): Hand Cream (various scents), Candle, Lip Balm' },
  { id: 9, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Givenchy', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Couture, streetwear-luxury, bags, shoes', products: 'BAGS: Antigona Soft Medium, Antigona Soft Small, Antigona Sport Small, Antigona Lock Soft, 4G Crossbody Bag, 4G Small Crossbody, Kenny Medium, Kenny Small, Moon Cut-Out Small, Moon Cut-Out Mini, Voyou Medium, Voyou Small, Shark Lock Ankle Boot Bag, Mini G-Tote, Medium G-Tote, Small Cut-Out Bag, Pandora Small, Pandora Mini\nSHOES: Shark Lock Boot Leather, Shark Lock Ankle Boot, Marshmallow Platform Slide, Marshmallow Wedge, TK-MX Runner Sneaker, TK-360 Sneaker, G4 Low Sneaker, City Sport Sneaker, Spectre Runner, 4G Slide, Voyou Sandal, Show Pump\nACCESSORIES: 4G Belt Reversible, 4G Logo Belt Thin, 4G Sunglasses Shield, GV Day Sunglasses, 4G Silk Scarf Square, 4G Logo Cap, 4G Beanie, GV Logo Tie\nRTW: 4G Logo Hoodie, 4G Logo Tee, 4G Denim Jacket, Oversized Bomber, Slim Fit Jeans, Logo Sweatshirt, Chain Link Dress, Lace Detail Top, Tailored Blazer' },
  { id: 10, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Goyard', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Hand-painted trunks, totes, bespoke leather', products: 'TOTES: St. Louis PM Tote (all colours), St. Louis GM Tote, St. Louis Junior, Anjou Mini, Anjou PM, Anjou GM, Artois PM, Artois MM, Hardy PM Dog Carrier, Sac Rouette\nSHOULDER & CROSS: Belvedère PM, Belvedère MM, Plumet Crossbody, Cap Vert Clutch, Saïgon Souple Mini, Saïgon Souple PM, Saïgon Structuré Mini, Saïgon Structuré PM, Vendôme Shoulder, Bohème Hobo\nSLG: Senat Pouch PM, Senat Pouch MM, Senat Pouch GM, Matignon PM Wallet, Matignon GM Wallet, Richelieu Long Wallet, Saint Sulpice Card Holder, Saint Marc Card Holder, Varenne Continental, Monte Carlo Jewel Case, Saint Léger Passport Case\nTRUNK & TRAVEL: Bourget PM Trolley, Bourget MM Trolley, Ambassade PM Briefcase, Ambassade MM, Boeing 45 Duffle, Boeing 55, Chaperon Hat Box, Voltigeur Garment Bag, Croisière 35 Travel Bag, Croisière 45, Chevron Luggage Tag, Chevron Belt, iPhone Case Chevron, AirPods Case' },
  { id: 11, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Gucci', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'RTW, bags, shoes, belts, eyewear, décor', products: 'WOMEN BAGS: GG Marmont Small Matelassé Shoulder, GG Marmont Mini, GG Marmont Medium, GG Marmont Super Mini, GG Marmont Chain Wallet, GG Marmont Belt Bag, Dionysus GG Supreme Small, Dionysus GG Supreme Medium, Dionysus GG Supreme Mini, Jackie 1961 Small Shoulder, Jackie 1961 Medium, Jackie 1961 Mini, Ophidia GG Small Tote, Ophidia GG Medium Tote, Ophidia GG Mini Crossbody, Horsebit 1955 Small Shoulder, Horsebit 1955 Mini, Bamboo 1947 Small Top Handle, Bamboo 1947 Medium, GG Matelassé Top Handle Mini, Blondie Small Shoulder, Gucci Savoy Medium Duffle, Gucci Savoy Toiletry Case, Petite GG Mini Shoulder, Luce Shoulder Bag\nMEN BAGS: GG Supreme Messenger, GG Canvas Belt Bag, Jumbo GG Messenger, Ophidia GG Sling Backpack, GG Supreme Backpack, GG Marmont Belt Bag Men, Interlocking G Messenger, Jumbo GG Tote, GG Duffle Bag\nSHOES WOMEN: Ace Embroidered Sneaker Bee, Ace GG Supreme Sneaker, Ace Platform Sneaker, Rhyton Logo Sneaker, Screener GG Sneaker, Run Sneaker, Princetown Horsebit Mule, Princetown GG Supreme, Jordaan GG Loafer, Jordaan Horsebit Loafer, Horsebit Slingback Pump, GG Marmont Platform Sandal, GG Slide Sandal, Platform Slide Web, GG Espadrille\nSHOES MEN: Ace Sneaker Classic, Ace Loved Sneaker, Rhyton Sneaker Men, Screener Sneaker Men, Horsebit Loafer Leather, Jordaan Loafer Men, Web Slide Sandal, Driver Moccasin, Horsebit Boot, Chelsea Boot GG\nBELTS: GG Marmont Leather Belt 4cm, GG Marmont Thin Belt 2cm, GG Supreme Canvas Belt, GG Canvas Belt Web, Interlocking G Belt 3.5cm, Interlocking G Belt Slim, Double G Buckle Belt, Reversible GG Belt, GG Belt with Snake Buckle, Horsebit Belt, Web Belt Elastic\nEYEWEAR: Aviator Metal Frame, Square Oversize, Cat Eye Acetate, Round Metal, Rectangular, Navigator, Pilot, Mask, Rimless, GG Logo Temple\nACCESSORIES: GG Wool Scarf Jacquard, GG Supreme Canvas Cap, Silk GG Print Scarf Square, GG Pattern Silk Tie, Web Stripe Tie, GG Canvas Hat Bucket, Gucci Logo Beanie, GG Canvas Bomber, Flora Print Silk Dress, Logo Hoodie Oversized, Logo Tee Vintage, Web Stripe Polo, GG Jacquard Sweater, GG Denim Jacket, GG Swim Trunk, Horsebit Print Shirt\nDÉCOR: GG Logo Cushion, Bee Print Mug, Herbarium Tray, Flora Candle' },
  { id: 12, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Hermès', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Birkin, Kelly, scarves, leather, equestrian, home', products: 'WOMEN BAGS: Birkin 25 Togo Gold, Birkin 25 Togo Black, Birkin 25 Togo Etoupe, Birkin 25 Epsom, Birkin 30 Togo Gold, Birkin 30 Togo Black, Birkin 30 Togo Etain, Birkin 30 Clemence, Birkin 35 Togo, Birkin 35 Clemence, Kelly 25 Epsom, Kelly 25 Togo, Kelly 28 Epsom, Kelly 28 Togo, Kelly 28 Sellier Epsom, Kelly 32 Togo, Kelly 32 Clemence, Kelly Pochette, Kelly To Go, Kelly Danse, Picotin Lock 18, Picotin Lock 22, Constance 18 Epsom, Constance 24, Constance Mini, Garden Party 30, Garden Party 36 Negonda, Evelyne III 16 TPM, Evelyne III 29 PM, Evelyne III 33 GM, Lindy 26 Clemence, Lindy 30, Bolide 27, Bolide 31, Herbag Zip 31, Herbag Zip 39, Halzan 25, Halzan 31, Roulis 18, Roulis 23, Kelly Ado Backpack, Jypsiere 28, 24/24 29, Mini Kelly 20\nSCARVES & SHAWLS: Carré 90 Silk Twill (200+ print designs rotate), Carré 70 Silk, Twilly d\'Hermès Pair, Twilly Slim, Maxi Twilly Silk, Losange Silk, Bandana 55, Plissé Silk Scarf, Stole Cashmere & Silk 75x210, Grand H Cashmere Blanket Scarf, Triangle Géant Silk\nSHOES WOMEN: Oran Sandal Classic Gold, Oran Sandal Epsom Black, Oran Sandal Epsom various colors, Oasis Sandal, Galop Boot, Kelly Buckle Boot, Fantaisie Mule, Egérie Pump, Day Sneaker, Bouncing Sneaker, Femme Sneaker, Entr\'acte Sandal, Avenue Sandal, Première Ankle Boot, Duo Slide\nBELTS: H Buckle Belt 32mm Reversible, H Buckle Belt 42mm, H Buckle Belt 13mm Women, Mini Constance Belt 24mm, Etrivière 40mm, Oscar Belt Buckle, Gamma Belt, Cape Cod Belt\nHOME & LIFESTYLE: Avalon Throw Blanket Ecru/Orange, Avalon Baby Blanket, Mosaïque au 24 Dinner Plate, Mosaïque au 24 Tea Cup & Saucer, Bleus d\'Ailleurs Dinner Plate, Balcon du Guadalquivir Tea Cup, Carnets d\'Equateur Tray, Saut Hermès Ashtray, Rallye 24 Mug, Beach Towel Printed' },
  { id: 13, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Jimmy Choo', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Evening shoes, heels, boots, bags, sneakers', products: 'WOMEN SHOES: Romy 85 Patent, Romy 100 Suede, Romy 60 Leather, Bing 65 Glitter Slingback, Bing 100, Love 85 Patent, Love 100 Suede, Love 65, Saeda 100 Platform, Saeda 85, Aveline 100 Bow, Bon Bon 100, Sacaria 120 Platform, Azia 95 Strappy, Azia 110, Ixia 95, Lang 100, Varenne Pump 85, Abel Pointed Flat, Ade Flat, Diamond Mavis Sneaker, Hawaii Sneaker, Memphis Sneaker, Nell Boot 85, Cora Boot 100, Mahesa Boot 70, Yael Slide, Fimme Slide, Sacora 100 Pearl, Romy Flat Ballet, Art Mule 50\nMEN SHOES: Diamond Light Sneaker, Diamond Mavis Sneaker, Hawaii Sneaker, Palma Loafer, Foxley Tassel Loafer, Thame Oxford, Aitch Monk, Bari Boot, Cruz Combat, Slide Avenue, Edson Moccasin\nBAGS: Bon Bon Bucket, Varenne Hobo Small, Varenne Quad, Varenne Shoulder, Madeline Shoulder, Callie Clutch Crystal, Cloud Clutch, Emmie Clutch Glitter, Avenue Quad Crossbody, Diamond Crossbody, Avenue Tote, Nine2Five Tote, Pegasi Phone Case\nACCESSORIES: Cat Eye Sunglasses, Square Sunglasses, Aviator Sunglasses, JC Logo Belt, JC Buckle Belt, Silk Scarf JC' },
  { id: 14, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Loro Piana', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Cashmere, vicuña, baby cashmere, outerwear, travel', products: 'WOMEN: Baby Cashmere Sweater Crewneck, Baby Cashmere V-Neck, Baby Cashmere Cardigan, Baby Cashmere Turtleneck, Cashmere Silk Sweater, Cashmere Bomber Jacket, Cashmere Coat Long, Traveller Jacket Windmate, Wind Bomber Storm System, Horsey Cashmere Jacket, Summer Walk Shoe, Suede Loafer, Suede Ankle Boot, Sesia Bag Small, Sesia Bag Medium, Extra Pocket Pouch L19, Extra Pocket Pouch L27, Bale Bag, Loom Bag, Micro Bag, Cashmere Scarf Grande Unita, Cashmere Shawl, Vicuña Scarf, Baby Cashmere Beanie, Baby Cashmere Gloves\nMEN: Baby Cashmere Crewneck Sweater, Baby Cashmere V-Neck, Baby Cashmere Half-Zip, Cashmere Polo, Cashmere Zip Hoodie, Cashmere Jogger, Cashmere Blazer, Summer Walk Shoe, City Walk Sneaker, Open Walk Boot, Traveller Jacket Storm System, Rain System Parka, Linen Shirt, Cotton Polo André, Cotton Tee, Denim Five-Pocket, Slim Trouser, Bermuda Short, Silk Tie, Cashmere Scarf, Vicuña Scarf, Cashmere Beanie, Extra Pocket Backpack, Weekender Bag\nTRAVEL: Travel Kit Pouch, Passport Holder, Luggage Tag, Travel Blanket Cashmere, Eye Mask Cashmere, Socks Cashmere\nHOME: Cashmere Throw Interweave, Baby Cashmere Throw, Cashmere Pillow' },
  { id: 15, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Louis Vuitton', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Handbags, leather goods, RTW, shoes, travel, accessories', products: 'WOMEN BAGS: Neverfull MM Monogram, Neverfull GM Monogram, Neverfull MM Damier Ebene, Neverfull PM Monogram, Speedy Bandoulière 25, Speedy Bandoulière 30, Speedy Bandoulière 20, Alma BB Epi, Alma PM Monogram, Alma PM Damier Ebene, OnTheGo GM Empreinte, OnTheGo MM Monogram, Pochette Accessoires Monogram, Pochette Métis Monogram, Pochette Métis Empreinte, Multi Pochette Accessoires, Félicie Pochette, Capucines MM Taurillon, Capucines BB, Capucines Mini, Twist MM Epi, Twist PM, Dauphine MM, Dauphine Mini, Petite Malle, Coussin PM, Keepall Bandoulière 45, Keepall Bandoulière 50, Keepall Bandoulière 55, Keepall XS, Horizon 55 Rolling Luggage, Horizon 50\nMEN BAGS: Christopher PM Backpack, Christopher MM, Discovery Backpack PM, Trio Messenger, Avenue Sling Bag, S Lock Messenger, Soft Trunk, Steamer PM, Steamer Wearable, District PM Damier, Outdoor Messenger, Utility Crossbody, City Keepall\nSMALL LEATHER GOODS: Zippy Wallet Monogram, Zippy Wallet Empreinte, Clémence Wallet Monogram, Victorine Wallet, Sarah Wallet, Rosalie Coin Purse, Card Holder Monogram, Pocket Organizer Monogram, Brazza Wallet Men, Slender Wallet Men, Multiple Wallet, Key Pouch Monogram, Passport Cover Monogram, Toiletry Pouch 26, Toiletry Pouch 19, Nice Nano Vanity, Nice Mini Vanity\nWOMEN SHOES: Archlight Sneaker, Archlight 2.0 Platform, Time Out Sneaker White, Time Out Sneaker Gold, Stellar Sneaker, Frontrow Sneaker, Run Away Sneaker, LV Shake Pump 85mm, LV Shake Pump 55mm, LV Shake Ankle Boot, Silhouette Ankle Boot, Laureate Platform Desert Boot, Laureate Flat Sandal\nMEN SHOES: LV Trainer Sneaker White, LV Trainer Monogram Denim, LV Trainer Maxi, Fastlane Sneaker, Beverly Hills Sneaker, Rivoli Sneaker, Trocadéro Sneaker, Luxembourg Sneaker, Major Loafer, Monte Carlo Moccasin, Hockenheim Moccasin, Arizona Mule, Landscape Ankle Boot\nBELTS & ACCESSORIES: LV Initiales Belt 40mm Monogram, LV Initiales Belt 30mm, LV Shape Belt 40mm, LV Circle Belt, Reversible Monogram Belt, Monogram Shawl 140x140, Logomania Shine Scarf, Monogram Gradient Scarf, 1.1 Millionaires Sunglasses, LV Clash Square Sunglasses, LV Waimea Sunglasses, LV Moon Cat Eye, LV Blaze Mask, LV Evidence' },
  { id: 16, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Saint Laurent (YSL)', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Tuxedos, leather, boots, bags, RTW', products: 'BAGS: Loulou Puffer Small, Loulou Puffer Medium, Loulou Puffer Toy, Loulou Small, Loulou Medium, Kate Chain Bag Medium, Kate Chain Bag Small, Kate Tassel, Sac de Jour Nano, Sac de Jour Small, Sac de Jour Baby, Manhattan Shoulder Small, Manhattan Shoulder Medium, Niki Medium, Niki Baby, Niki Large, Le 5 à 7 Hobo, Le 5 à 7 Supple, Solferino Soft Small, Solferino Soft Medium, Cassandre Phone Holder, Sunset Medium, Envelope Medium, Puffer Toy Crossbody, June Box Bag, Icare Maxi Shopping Bag\nSHOES: Wyatt Chelsea Boot 40mm, Wyatt Harness Boot 40mm, Lou Chelsea Boot, Court Classic Sneaker, Court Classic Platform, Venice Skate Sneaker, Tribute Platform Sandal 105, Opyum Pump 110, Opyum Pump 85, La 16 Boot, Blake Jodhpur Boot, Tab Slide, Jimmy Sandal Flat, Cassandre Espadrille\nBELTS: Cassandre Belt Thin, Cassandre Belt Wide, YSL Initiales Belt 3cm, YSL Logo Belt\nEYEWEAR: SL 1 Shield, SL 28 Round, SL 276 Mica Square, SL 51 Cat Eye, SL Monogram Heart, SL M94 Aviator\nACCESSORIES: Leopard Print Silk Scarf, Logo Wool Scarf, Logo Beanie, Logo Baseball Cap\nRTW: Teddy Jacket Shearling, Leather Biker Jacket Classic, Tuxedo Jacket Grain de Poudre, Silk Pussy-Bow Blouse, Logo Print Tee, Logo Hoodie, Skinny Jean, Boyfriend Jean, Sequin Mini Dress, Draped Jersey Dress' },
  { id: 17, cat: '👗 Fashion & Luxury', tier: '💎 High-End', name: 'Salvatore Ferragamo', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Shoes, Gancini bags, ties, belts', products: 'WOMEN SHOES: Vara Bow Pump 70mm, Vara Bow Pump 40mm, Vara Bow Pump Patent, Varina Ballet Flat, Varina Bow Flat, Gancini Heel Pump, Gancini Sandal 55, Good Sneaker, Gancini Slide, Gancini Mule, Stivale Boot, Knee Boot\nMEN SHOES: Gancini Loafer, Gancini Bit Loafer, Benford Oxford, Angiolo Monk, Cube Sneaker, Gancini Sneaker, Detroit Sneaker, Desert Boot, Gancini Slide Men\nBAGS: Gancini Crossbody Mini, Gancini Top Handle, Gancini Chain Bag, Studio Bag Small, Studio Bag Medium, Wanda Shoulder, Viva Bow Tote, Hug Bag Small, Hug Bag Medium, Trifolio Crossbody, Ferragamo Logo Tote, Briefcase Business\nSLG: Gancini Card Holder, Gancini Zip Wallet, Continental Wallet, Bifold Wallet Men, Gancini Money Clip, Gancini Key Holder\nBELTS: Gancini Buckle Belt Reversible 35mm, Gancini Buckle Belt 30mm Women, Adjustable Gancini Belt, Double Gancini Belt, Vara Bow Belt\nACCESSORIES: Gancini Silk Tie, Gancini Pocket Square, Gancini Sunglasses, Navigator Sunglasses, Gancini Scarf Silk, Gancini Wool Scarf' },
  { id: 18, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'COS', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Modern essentials, architectural design, H&M premium', products: 'WOMEN: Draped Midi Dress, Knitted Column Dress, Pleated Midi Skirt, Tailored Wide-Leg Trouser, Oversized Blazer, Deconstructed Blazer, Oversized Shirt, Silk Shirt, Merino Wool Sweater, Cashmere Sweater, Ribbed Tank, Jersey Tee, Relaxed-Fit Tee, Cropped Cardigan, Padded Coat, Quilted Jacket, Leather Jacket, Trench Coat, Wide-Leg Jean, Straight-Leg Jean, Barrel-Leg Jean, Yoga Legging, Yoga Bra, Active Crop\nMEN: Relaxed-Fit Tee, Oversized Tee, Regular-Fit Oxford, Camp-Collar Shirt, Knitted Polo, Merino Wool Sweater, Cashmere Roll-Neck, Oversized Hoodie, Relaxed Jogger, Regular-Fit Chino, Barrel-Leg Jean, Straight-Leg Jean, Padded Coat, Lightweight Jacket, Quilted Vest, Elasticated Trouser\nACCESSORIES: Quilted Crossbody, Leather Tote, Leather Card Holder, Leather Belt, Leather Sneaker, Chunky Sneaker, Leather Sandal, Wool Scarf, Cashmere Beanie, Silk Scarf' },
  { id: 19, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Calvin Klein', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Minimalist fashion, underwear, jeans', products: 'TOPS: CK Institutional Logo Tee, CK Jeans Logo Tee, CK Logo Hoodie, CK Logo Crew Sweatshirt, CK Cotton Stretch Tee, CK Slim Fit Shirt, CK Relaxed Shirt, CK Linen Shirt, CK Knit Sweater, CK Cardigan\nBOTTOMS: CK Slim Straight Jean, CK Skinny Jean, CK Mom Jean, CK Wide Leg Jean, CK Slim Fit Chino, CK Jogger, CK Short, CK Suit Trouser, CK Swim Trunk\nSUITS: CK Slim Fit Suit Jacket, CK Slim Fit Suit Trouser, CK Wool Blazer\nOUTERWEAR: CK Puffer Jacket, CK Bomber, CK Denim Jacket, CK Wool Coat, CK Trench Coat\nWOMEN: CK Slip Dress, CK Midi Dress, CK Shirt Dress, CK Pleated Skirt, CK Wide Leg Trouser, CK Bodysuit, CK Crop Top\nUNDERWEAR: CK Modern Cotton Bralette, CK Modern Cotton Bikini Brief, CK Modern Cotton Thong, CK Modern Cotton Boyshort, CK Carousel Bikini 3-Pack, CK One Cotton Bralette, CK Cotton Stretch Trunk 3-Pack Men, CK Cotton Stretch Boxer 3-Pack, CK Micro Hip Brief 3-Pack, CK Steel Cotton Trunk\nBELTS & ACCESSORIES: CK Mono Card Case, CK Logo Belt Leather, CK Reversible Belt, CK Backpack, CK Crossbody, CK Tote Shopper, CK Wallet Zip, CK Cap, CK Beanie, CK Socks 3-Pack\nSHOES: CK Logo Sneaker, CK Chunky Cupsole, CK Lace-Up Runner, CK Slide, CK Loafer' },
  { id: 20, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Hugo Boss', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Suits, formalwear, casual, athleisure', products: 'SUITS: BOSS Slim Fit Suit Huge/Genius, BOSS Regular Fit Suit Jeckson/Lenon, BOSS Extra-Slim Suit Reymond/Wenten, BOSS Relaxed Fit Suit Hanry/Perin, BOSS H-Lenon Tuxedo, BOSS Slim Fit Blazer, BOSS Regular Fit Blazer, BOSS Tailored Trouser Slim, BOSS Tailored Trouser Regular\nSHIRTS: BOSS Regular Fit Shirt, BOSS Slim Fit Shirt, BOSS Jersey Shirt, BOSS Oxford Shirt, BOSS Tuxedo Shirt, BOSS Printed Shirt, BOSS Linen Shirt, BOSS Polo Shirt Piqué, BOSS Paddy Polo, BOSS Paule Slim Polo, BOSS Parlay Polo, BOSS Passertip Polo\nT-SHIRTS: BOSS Thinking Tee, BOSS Tiburt Logo Tee, BOSS Thompson Jersey, BOSS Tee 1, BOSS Tee Curved, BOSS Tales Plain Tee\nBOTTOMS: BOSS Delaware Slim Fit Jean, BOSS Maine Regular Jean, BOSS Schino-Slim Chino, BOSS Kaito Trouser, BOSS Track Pant, BOSS Headlo Jogger, BOSS Swim Short\nKNITWEAR: BOSS Pacello Crewneck, BOSS Amador Zip-Neck, BOSS Musso V-Neck, BOSS Bassari Cardigan, BOSS Cashmere Sweater\nOUTERWEAR: BOSS Malte Coat, BOSS Hyde Parka, BOSS Down Jacket, BOSS Leather Jacket, BOSS Bomber Jacket, BOSS Denim Jacket, BOSS Gilet\nACCESSORIES: BOSS Logo Cap, BOSS Scarf, BOSS Beanie, BOSS Leather Belt, BOSS Woven Belt, BOSS Card Holder Leather, BOSS Bifold Wallet, BOSS Messenger Bag, BOSS Weekender Bag, BOSS Tie Silk, BOSS Pocket Square, BOSS Socks 2-Pack, BOSS Underwear 3-Pack Trunk\nSHOES: BOSS Sneaker Titanium, BOSS Saturn Lowp, BOSS Baltimore Derby, BOSS Colby Monk, BOSS Lisbon Derby Boot, BOSS Larry Loafer, BOSS Slide Sandal' },
  { id: 21, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Kate Spade', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Colourful handbags, accessories, dresses', products: 'BAGS: Sam Icon Small Tote, Sam Icon Medium Tote, Sam Icon Convertible Crossbody, Knott Medium Crossbody, Knott Large Tote, Knott Flap Crossbody, Morgan Satchel Double Zip, Morgan Dome Crossbody, Spade Flower Jacquard Tote, All Day Large Tote, All Day Zip Top Tote, Manhattan Small Tote, Manhattan Large Tote, Leila Medium Flap Shoulder, Staci Dome Crossbody, Staci Satchel, Carson Convertible, Gramercy Medium Flap Shoulder, Dakota Medium Satchel, Rosie Crossbody\nSLG: Spencer Card Holder, Spencer Zip Wallet, Spencer Bifold, Morgan Card Holder, Morgan Zip Around, Leila Card Case, Phone Crossbody Wallet, Wristlet, Coin Purse Novelty\nSHOES: Kate Spade Sneaker, Lounge Sneaker, Merritt Flat, Veronica Pump, Flamenco Sandal, Boardwalk Slide\nACCESSORIES: KS Sunglasses Cat Eye, KS Sunglasses Square, KS Silk Scarf, KS Hair Accessories, KS Umbrella, KS Phone Case, KS Key Fob Novelty\nRTW: Midi Dress Floral, Shirt Dress, Knit Dress, Floral Blouse, Cardigan, Denim, Skirt' },
  { id: 22, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Massimo Dutti', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Refined casual, suits, knitwear, Inditex premium', products: 'MEN: Wool Suit Blazer Regular Fit, Wool Suit Blazer Slim, Wool Suit Trouser, Linen Suit Blazer, Cotton Suit Blazer, Regular Fit Oxford Shirt, Slim Fit Shirt, Linen Shirt, Premium Cotton Tee, Polo Shirt, Knit Polo, V-Neck Sweater, Crewneck Sweater, Cashmere Blend Sweater, Cardigan, Hoodie, Jogger Pant, Chino Pant, Straight Fit Trouser, Slim Fit Jean, Denim Jacket, Leather Jacket, Wool Coat, Puffer Jacket, Bermuda Short, Swim Trunk\nWOMEN: Blazer Fitted, Blazer Oversized, Linen Blazer, Tailored Trouser, Wide Leg Trouser, High Rise Straight Jean, Culottes, Pleated Skirt, Midi Dress, Shirt Dress, Knit Dress, Silk Blouse, Linen Shirt, Cotton Tee, Cashmere Sweater, Cardigan Knit, Leather Jacket, Wool Coat, Trench Coat, Puffer Jacket\nACCESSORIES: Nappa Leather Belt, Woven Belt, Leather Card Case, Leather Wallet, Leather Tote, Crossbody Bag, Leather Loafer, Suede Loafer, Leather Sneaker, Ankle Boot, Flat Sandal, Heeled Mule, Silk Scarf, Sunglasses\nLEATHER: Nappa Leather Bag, Suede Crossbody, Leather Backpack, Leather Briefcase' },
  { id: 23, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Michael Kors', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Handbags, RTW, jet-set lifestyle', products: 'BAGS: Jet Set Travel Large Chain Tote, Jet Set Travel Medium Tote, Mercer Medium Accordion Satchel, Mercer Large Convertible Tote, Hamilton Legacy Large Satchel, Hamilton Legacy Medium Satchel, Voyager East West Tote, Rhea Medium Backpack, Rhea Zip Backpack, SoHo Large Quilted Shoulder, Cece Chain Shoulder, Cece Small Shoulder, Parker Convertible Shoulder, Whitney Shoulder, Carmen Satchel, Karlie Tote, Heather Extra-Large Tote\nSLG: Jet Set Travel Card Case, Jet Set Zip Continental, Jet Set Coin Pouch, Slim Bifold Wallet, Large Trifold Wallet, Phone Crossbody Wallet, Wristlet Large\nSHOES: Keaton Lace-Up Sneaker, Irving Lace-Up, Allie Trainer, Dorothy Flex Pump, Samira Flat Sandal, Kensington Riding Boot, Colby Sneaker\nACCESSORIES: MK Logo Belt Reversible, MK Logo Sunglasses, MK Logo Scarf, MK Logo Beanie, MK Logo Gloves' },
  { id: 24, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Ralph Lauren', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Polo, suits, American heritage, home', products: 'POLO SHIRTS: Slim Fit Mesh Polo (20+ colors), Classic Fit Mesh Polo (20+ colors), Custom Slim Fit Polo, Big Pony Polo, Interlock Polo, Featherweight Mesh Polo, Soft Cotton Polo, Long-Sleeve Mesh Polo, Performance Polo\nTOPS: Polo Bear Sweater, Cable-Knit Cotton Sweater, Cable-Knit Cashmere Sweater, Aran-Knit Sweater, Merino Wool V-Neck, Pima Cotton Crewneck, Jersey Crewneck Tee, Classic Fit Jersey Tee, Custom Slim Fit Tee, Oxford Shirt, Custom Fit Oxford, Slim Fit Oxford, Linen Shirt, Chambray Shirt, Western Shirt, Flannel Plaid Shirt, Performance Hoodie, Double-Knit Hoodie, Fleece Hoodie, Double-Knit Full-Zip\nBOTTOMS: Sullivan Slim Stretch Jean, Hampton Relaxed Straight Jean, Varick Slim Straight, Stretch Chino Pant, Classic Fit Chino, Stretch Slim Fit Chino, Stretch Straight Fit Pant, Double-Knit Jogger, Fleece Jogger, Performance Short, Swim Trunk\nSUITS & TAILORING: Polo Soft Suit Jacket, Gregory Blazer, Sport Coat, Tuxedo Jacket, Wool Trouser, Dress Shirt\nOUTERWEAR: Quilted Down Vest, Packable Down Jacket, Bi-Swing Windbreaker, Lined Coach Jacket, Water-Repellent Bomber, Double-Breasted Wool Coat\nACCESSORIES: Leather Belt Saddle, Reversible Belt, Big Pony Cap, Classic Sport Cap, Polo Bear Cap, Polo Bear Scarf, Cable-Knit Beanie, Leather Card Case, Billfold Wallet, Weekend Tote Canvas, Polo Sport Duffel\nHOME: Polo Bear Pillow, Cable-Knit Throw, RL Cable Cashmere Throw, Polo Player Towel' },
  { id: 25, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Ted Baker', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Smart-casual British fashion, quirky prints, accessories', products: 'MEN: Nikkon Polo, Campa Polo, Regular Fit Oxford Shirt, Slim Fit Shirt, Paisley Print Shirt, Logo Tee, Graphic Tee, Wool Suit Jacket, Slim Fit Trouser, Chino Pant, Denim Jean, Jersey Jogger, Bomber Jacket, Blazer, Mac Coat, Quilted Jacket, Harrington, Logo Hoodie, Logo Sweatshirt, Knit Sweater, Silk Tie, Pocket Square\nWOMEN: Bodycon Dress, Shift Dress, Wrap Dress, Skater Dress, Blazer Fitted, Tailored Trouser, Floral Blouse, Knit Sweater, Logo Tee, Leather Jacket, Wool Coat, Pleated Skirt, Denim\nBAGS: Milah Bow Detail Clutch, Amasoni Icon Tote, Jimsie Top Handle, Doliia Crossbody, Harliee Crossbody, Myycon Card Holder, Croc Effect Tote, Knot Bow Cosmetic Case\nSHOES: Paiton Sneaker, Leather Derby, Monk Shoe, Loafer, Chelsea Boot Women, Heeled Boot, Bow Detail Flat, Platform Sandal\nACCESSORIES: TB Logo Belt, Pearl Stud, iPhone Case, Umbrella, Washbag, Scarf, Beanie' },
  { id: 26, cat: '👗 Fashion & Luxury', tier: '🏷️ Mid-Range', name: 'Tommy Hilfiger', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Preppy American fashion, sportswear, denim', products: 'POLOS: TH Essential Polo Regular (15+ colours), TH Slim Fit Polo, TH 1985 Regular Polo, TH Flag Polo, TH Tipped Polo\nT-SHIRTS: TH Flag Logo Tee, TH Script Logo Tee, TH Essential Logo Tee, TH Graphic Tee, TH Stripe Tee, TH Corp Tee\nSHIRTS: TH Core Flex Shirt, TH Regular Fit Oxford, TH Slim Fit Shirt, TH Linen Shirt, TH Check Shirt, TH Denim Shirt\nSWEATERS: TH Flag Hoodie, TH Essential Hoodie, TH Logo Crew Sweatshirt, TH Half-Zip Knit, TH Cotton Cashmere Sweater, TH Cable-Knit\nBOTTOMS: Slim Bleecker Chino, Denton Straight Jean, Scanton Slim Jean, Core Straight Denton, Harlem Relaxed, TH Jogger, TH Short, TH Swim Trunk\nOUTERWEAR: TH Yacht Jacket, TH Puffer Jacket, TH Bomber Jacket, TH Denim Jacket, TH Leather Jacket, TH Raincoat\nWOMEN: TH Essential Midi Dress, TH Shirt Dress, TH Polo Dress, TH Pleated Skirt, TH Wide Leg Pant, TH Legging, TH Crop Top\nACCESSORIES: TH Signature Sneaker, TH Canvas Sneaker, TH Leather Sneaker, TH Runner, TH Slide, TH Crossbody, TH Tote, TH Backpack, TH Belt Leather, TH Logo Cap, TH Beanie, TH Scarf, TH Wallet, TH Card Holder, TH Socks 2-Pack, TH Underwear Trunk 3-Pack' },
  { id: 27, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'H&M', mall: 'Dubai Mall', location: 'Ground Floor (2 levels)', spec: 'Affordable fashion, basics, home', products: 'WOMEN: Slim Fit Cotton Tee, Relaxed Fit Tee, V-Neck Tee, Ribbed Tank Top, Oversized Hoodie, Regular Fit Hoodie, Zip-Through Hoodie, Sweatshirt Relaxed, Jersey Dress, Satin Wrap Dress, Shirt Dress, Knit Dress, Fine-Knit Cardigan, Oversized Cardigan, Cable-Knit Sweater, Turtleneck Sweater, Straight Regular Jeans, Mom High Ankle Jeans, Wide High Jeans, Slim Fit Jeans, Linen Blend Shirt, Poplin Shirt, Satin Blouse, Blazer Single-Breasted, Tailored Trousers, Chinos, Cargo Pants, Ribbed Legging, Midi Skirt Satin, Mini Skirt Denim, Biker Jacket Faux Leather, Puffer Jacket, Teddy Coat, Wool-Blend Coat\nMEN: Slim Fit Cotton Tee, Regular Fit Tee, Oversized Tee, Regular Fit Hoodie, Zip-Through Hoodie, Sweatshirt, Slim Fit Jeans, Straight Regular Jeans, Relaxed Fit Jeans, Regular Fit Chinos, Slim Fit Chinos, Joggers, Oxford Shirt, Regular Fit Shirt, Linen Shirt, Polo Shirt, Fine-Knit Sweater, Cotton Cardigan, Blazer Slim Fit, Suit Trouser, Down Jacket, Bomber Jacket, Shirt Jacket, Swim Short\nSHOES: Canvas Sneaker, Platform Sneaker, Ankle Boots, Chelsea Boots, Loafers, Sandals Flat, Block Heel Sandal, Slides\nACCESSORIES: Shopper Bag, Crossbody Bag, Bucket Hat, Cap, Beanie, Scarf, Belt Leather, Sunglasses, Hair Accessories\nHOME: Cotton Bedding Set, Cushion Cover, Throw Blanket, Towel, Candle Scented, Vase, Storage Basket' },
  { id: 28, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Mango', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Mediterranean fashion, workwear, dresses, accessories', products: 'WOMEN: Linen Blend Suit Blazer, Oversized Blazer, Double-Breasted Blazer, Flowy Midi Dress, Printed Shirt Dress, Knit Dress, Satin Slip Dress, Cotton Midi Dress, Straight-fit Jeans, Wideleg Jeans, Culotte Jeans, Mom Jeans, Knitted Cardigan, Crochet Top, Basic Cotton Tee, Oversized Tee, Linen Shirt, Printed Blouse, Satin Blouse, Tailored Trouser, Wide-Leg Trouser, Cargo Pant, Pleated Skirt, Leather-Effect Skirt, Trench Coat, Wool Coat, Puffer Jacket, Denim Jacket, Leather-Effect Jacket\nMEN: Slim-Fit Suit Blazer, Regular-Fit Blazer, Suit Trouser, Oxford Shirt, Regular Fit Shirt, Slim Fit Shirt, Linen Shirt, Cotton Polo, Basic Tee, Logo Tee, Slim-Fit Jean, Regular-Fit Jean, Chino Trouser, Bermuda Short, Swim Trunk, Hoodie, Sweatshirt, Knit Sweater, Bomber Jacket, Denim Jacket, Wool Coat, Down Jacket\nSHOES: Platform Sandal, Heeled Mule, Loafer, Ankle Boot, Chelsea Boot, Sneaker, Flat Sandal, Espadrille\nBAGS: Shopper Tote Bag, Crossbody Bag, Bucket Bag, Clutch, Leather Belt, Sunglasses' },
  { id: 29, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Max Fashion', mall: 'Various (15+)', location: 'Multiple malls', spec: 'Value fashion, family, basics, ethnic', products: 'MEN: Striped Polo Tee, Solid Crew Tee, Printed Tee, Regular Fit Shirt, Checked Shirt, Hoodie, Sweatshirt, Jogger, Skinny Jean, Straight Jean, Chino, Bermuda, Swim Trunk, Bomber Jacket, Vest, Belt, Socks Pack, Boxer Pack, Thobe, Kandura\nWOMEN: Solid Tee, Printed Tee, Blouse, Tunic, Maxi Dress, Midi Dress, Printed Maxi, Legging, Jegging, Denim Skinny, Wide Leg Pant, Cardigan, Pullover, Jacket, Abaya, Kaftan, Jalabiya, Hijab, Salwar Kameez, Kurti\nKIDS: Graphic Tee, Printed Dress Girls, Denim Boys, Jogger Kids, Character Pyjama, School Uniform Polo, School Uniform Trouser\nSHOES: Slip-On Shoe, Canvas Sneaker, Sandal, Slide, School Shoe\nACCESSORIES: Crossbody Bag, Backpack, Belt, Sunglasses, Jewellery Set' },
  { id: 30, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Nike', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Athletic footwear, sportswear, Jordan, running', products: 'SHOES: Air Force 1 \'07 White, Air Force 1 \'07 Black, Air Force 1 Low Various, Air Max 90 White, Air Max 90 Various, Air Max 95, Air Max 97, Air Max Plus, Air Max DN, Dunk Low Panda, Dunk Low Retro Various, Dunk High, Air Jordan 1 Mid, Air Jordan 1 Low, Air Jordan 1 High OG, Air Jordan 4 Retro, Air Jordan 3, Air Jordan 11, Pegasus 41, Vomero 17, InfinityRN 4, Structure 25, Winflo 11, Free Metcon 6, Zoom Fly 6, Vaporfly 3, Alphafly 3, Court Vision Low, Blazer Mid \'77, Blazer Low, Cortez, Killshot 2, Air Rift, ACG Mountain Fly 2, Air Monarch IV\nAPPAREL: Dri-FIT Tee, Dri-FIT Polo, Dri-FIT Tank, Tech Fleece Full-Zip Hoodie, Tech Fleece Jogger, Tech Fleece Vest, Club Fleece Hoodie, Club Fleece Jogger, Club Fleece Crew, Sportswear Windrunner Jacket, Pro Tight Legging, Pro Short, Pro Sports Bra, One Legging, One Short, One Tank, Therma-FIT Hoodie, ACG Jacket, ACG Short, Jordan Essentials Hoodie, Jordan Essentials Pant, Jordan Flight Tee\nACCESSORIES: Heritage86 Cap, H86 Futura Cap, Aerobill Cap, Club Cap, Brasilia Backpack, Elemental Backpack, Heritage Crossbody, Heritage Waist Pack, Hayward Backpack, Everyday Plus Cushioned Sock, Dri-FIT Sock 3-Pack, Swoosh Headband, Swoosh Wristband' },
  { id: 31, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Splash', mall: 'Various (20+)', location: 'Multiple malls', spec: 'GCC affordable fashion, basics, family', products: 'MEN: Printed Crew Neck Tee, Solid V-Neck Tee, Regular Fit Polo, Slim Fit Polo, Long Sleeve Shirt, Checked Shirt, Denim Shirt, Cotton Hoodie, Crew Sweatshirt, Jogger Pant, Skinny Jean, Straight Jean, Slim Fit Chino, Bermuda Short, Swim Short, Bomber Jacket, Denim Jacket, Puffer Vest, Belt, Cap, Socks 3-Pack, Boxer 3-Pack\nWOMEN: Printed Tee, Solid Basic Tee, Crop Top, Blouse, Tunic, Maxi Dress, Midi Dress, Shift Dress, Pleated Skirt, Denim Skirt, Legging, Skinny Jean, Wide Leg Pant, Jogger, Cardigan, Hoodie, Pullover Sweater, Jacket, Abaya Plain, Abaya Embellished, Hijab Scarf, Hijab Undercap\nKIDS: Graphic Tee Boys, Graphic Tee Girls, Denim Short, Jogger Pant Kids, Dress Girls, Polo Boys, Hoodie Kids, School Uniform\nSHOES: Canvas Sneaker, Slip-On Shoe, Sandal Flat, Slide, Sport Shoe\nACCESSORIES: Crossbody Bag, Backpack, Belt, Sunglasses, Hair Band Set' },
  { id: 32, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Uniqlo', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Japanese basics, HeatTech, AIRism, LifeWear', products: 'AIRism: AIRism Cotton Crew Neck Tee, AIRism Cotton V-Neck, AIRism Cotton Oversized, AIRism Mesh Boxer, AIRism Mesh Brief, AIRism Ultra Seamless Boxer, AIRism UV Protection Mesh Hoodie, AIRism UV Cut Cardigan, AIRism Body Shaper\nHEATTECH: HeatTech Crew Neck, HeatTech V-Neck, HeatTech Extra Warm Crew, HeatTech Ultra Warm Crew, HeatTech Tights, HeatTech Extra Warm Tights, HeatTech Ultra Warm Tights, HeatTech Socks\nBOTTOMS: Ultra Stretch Skinny Fit Jeans, Slim Fit Selvedge Jeans, Regular Fit Jeans, Wide Fit Jeans, EZY Ultra Stretch Jeans, Smart Ankle Pants 2-Way Stretch, Kando Pants, Dry Stretch Sweatpants, Relaxed Fit Ankle Pants, Ultra Stretch Active Jogger, Pleated Wide Pants, Baggy Jeans\nTOPS: Supima Cotton Crew Neck Tee (20+ colours), U Crew Neck Short Sleeve Tee, U Oversized Tee, Flannel Checked Shirt, Oxford Shirt, Linen Shirt, Premium Linen Shirt, Rayon Blouse, Extra Fine Merino V-Neck Sweater, Extra Fine Merino Crew Neck, Cashmere Crew Neck, Cashmere V-Neck, Souffle Yarn Crew Neck, Sweat Hoodie, Dry Sweat Hoodie, Fleece Full-Zip\nOUTERWEAR: Ultra Light Down Jacket, Ultra Light Down Vest, Ultra Light Down Parka, Ultra Light Down Coat, Hybrid Down Parka, Pufftech Jacket, Pufftech Vest, Blocktech Parka, Blocktech Coat, Fleece Jacket, Denim Jacket, Chore Jacket' },
  { id: 33, cat: '👗 Fashion & Luxury', tier: '🛒 Affordable', name: 'Zara', mall: 'Dubai Mall', location: 'Ground Floor (3 levels)', spec: 'Fast fashion, trend clothing, shoes, bags, home', products: 'WOMEN: Linen Blend Blazer, Cropped Blazer, Double Breasted Coat, Wrap Coat, Straight Leg Trouser, Wide Leg Full Length Jean, ZW Premium Straight Jean, ZW Premium High Rise, Mom Fit Jean, Flowing Printed Midi Dress, Satin Effect Midi Dress, Knit Midi Dress, Shirt Dress, Crop Top Ribbed, Basic Crew Neck Tee, Oversized Tee, Soft Feel Knit, Ribbed Knit Sweater, Cashmere Feel Sweater, Pleated Skirt Midi, Satin Skirt, Leather Effect Skirt, Tailored Bermuda, Cargo Pant Wide, Bodysuit Seamless, Lace Bodysuit, Poplin Shirt, Linen Shirt\nMEN: Comfort Suit Blazer, Textured Suit Blazer, Basic Suit Trouser, Slim Fit Oxford Shirt, Linen Shirt, Printed Shirt, Premium Cotton Tee, Basic Crew Tee, Polo Shirt Piqué, Knit Sweater, Hoodie Essential, Jogger Essential, Skinny Jean, Straight Jean, Relaxed Fit Jean, Cargo Pant, Chino Trouser, Bermuda Short, Swim Trunk\nSHOES: Block Heel Sandal, Platform Sneaker, Loafer Moccasin, Slingback Kitten Heel, Strappy Flat Sandal, Ankle Boot, Chelsea Boot, Minimalist Sneaker, Lace-Up Derby, Monochrome Sneaker\nBAGS: City Crossbody Bag, Bucket Bag Quilted, Shopper Tote, Chain Strap Bag, Clutch Evening, Backpack Urban\nACCESSORIES: Minimal Leather Belt, Fabric Belt, Sunglasses Square, Sunglasses Cat Eye, Hair Clip Set, Scarf Printed' },
  // SPORTS & ACTIVEWEAR
  { id: 34, cat: '⚽ Sports & Activewear', tier: '💎 High-End', name: 'TAG Heuer', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Luxury sports, F1, motorsport, diving', products: 'CARRERA: Carrera Date 36mm, Carrera Date 29mm, Carrera Three Hands 39mm, Carrera Plasma Diamant d\'Avant-Garde, Carrera Day-Date 41mm, Carrera Skipper\nAQUARACER: Aquaracer Professional 300 43mm, Aquaracer Professional 300 36mm, Aquaracer Professional 200 40mm, Aquaracer Professional 200 30mm, Aquaracer Professional 1000 Superdiver, Monaco Titan\nFORMULA 1: Formula 1 Quartz 43mm, Formula 1 Quartz 41mm, Formula 1 Lady 32mm, Formula 1 x Fragments\nCONNECTED: Connected Calibre E4 45mm, Connected Calibre E4 42mm, Connected Golf Edition\nOTHER: Link 41mm, Link Lady 32mm, Autavia Chronometer Flyback, Autavia 42mm GMT, Tag Heuer Monza' },
  { id: 35, cat: '⚽ Sports & Activewear', tier: '🏷️ Mid-Range', name: 'Lululemon', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Premium athleisure, yoga, running, lifestyle', products: 'WOMEN BOTTOMS: Align High-Rise Pant 25", Align High-Rise Pant 28", Align High-Rise Pant 31", Align High-Rise Short 6", Align High-Rise Short 8", Align High-Rise Crop 21", Wunder Train High-Rise Tight 25", Wunder Train High-Rise Tight 28", Wunder Train High-Rise Crop 21", Wunder Train High-Rise Short 6", Fast and Free High-Rise Tight 25", Fast and Free High-Rise Tight 28", Base Pace High-Rise Tight, Instill High-Rise Tight, All the Right Places Pant, Groove Pant Flare, Dance Studio Pant\nWOMEN TOPS: Define Jacket Luon, Define Jacket Nulu, Scuba Oversized Full-Zip Hoodie, Scuba Oversized Half-Zip, Scuba Funnel Neck Relaxed, Swiftly Tech Long Sleeve 2.0, Swiftly Tech Short Sleeve 2.0, Swiftly Tech Racerback, All Yours Tee, Classic-Fit Cotton Tee, Relaxed-Fit Crewneck, Love Tee, Softstreme Oversized Crew\nSPORTS BRAS: Energy Bra Long Line, Energy Bra, Free to Be Bra, Flow Y Bra, Like a Cloud Bra, Wunder Train Strappy Bra, Ribbed Nulu Bra\nMEN: ABC Jogger, ABC Slim-Fit Pant, Commission Pant Classic, Commission Short, Pace Breaker Short Lined, T.H.E. Short, Metal Vent Tech Polo 2.0, Metal Vent Tech Short Sleeve, Evolution Polo, Drysense Short Sleeve, City Sweat Hoodie, City Sweat Jogger, Steady State Crew, Surge Warm Full-Zip\nACCESSORIES: Everywhere Belt Bag 1L, Everywhere Belt Bag Extended, City Adventurer Backpack Mini, Nano Backpack, The Mat 5mm, Carry Onwards Travel Mat, Double Roller, Yoga Block Cork, Yoga Strap' },
  { id: 36, cat: '⚽ Sports & Activewear', tier: '🏷️ Mid-Range', name: 'The North Face', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Outdoor jackets, fleece, hiking, urban outdoor', products: 'JACKETS: 1996 Retro Nuptse Jacket (all colours), 1996 Retro Nuptse Vest, Thermoball Eco Jacket 2.0, Thermoball Eco Vest, Denali 2 Fleece Jacket, Denali Vest, 100 Glacier Full-Zip Fleece, 100 Glacier Half-Zip, Antora Waterproof Jacket, Venture 2 Jacket, Evolve II Triclimate, McMurdo Parka, Arctic Parka, Zaneck Jacket, Mountain Light Triclimate, Windwall Jacket\nTOPS: Simple Dome Tee, Box Logo Tee, Standard Tee, Redbox Tee, Drew Peak Hoodie, Drew Peak Crew, Light Drew Peak Hoodie, Mountain Athletics Tee, MA Tight, MA Hoodie, Half Dome Tee\nBOTTOMS: Exploration Pant, Convertible Pant, Paramount Active Pant, Standard Pant, Jogger, NSE Pant, Freedom Insulated Pant\nBACKPACKS: Borealis Backpack, Borealis Mini, Recon Backpack, Jester Backpack, Vault Backpack, Surge Backpack, Base Camp Duffel S, Base Camp Duffel M, Base Camp Duffel L, Base Camp Voyager Duffel\nSHOES: VECTIV Fastpack Futurelight, VECTIV Exploris 2, VECTIV Infinite 2, Hedgehog Futurelight, Thermoball Traction Bootie, Thermoball Traction Mule, Base Camp Slide\nACCESSORIES: Logo Beanie, Norm Hat, Etip Glove, Denali Etip Glove, Mudder Trucker Cap, Horizon Hat, Dryvent Hat, Dock Worker Beanie' },
  { id: 37, cat: '⚽ Sports & Activewear', tier: '🛒 Affordable', name: 'Decathlon', mall: 'Festival City / MoE area', location: 'Large format', spec: 'Budget sports gear, all equipment, own brands', products: 'QUECHUA (HIKING): MH500 Waterproof Jacket, MH100 Fleece, NH100 Backpack 10L, NH500 Backpack 20L, MH500 Hiking Shoe, MH100 Hiking Short, MH500 Trekking Pant, SH100 Snow Hiking Boot, MT100 Trekking Pole\nKALENJI (RUNNING): Run Support Shoe, Run Active Shoe, Run Comfort Shoe, Kiprun KS900 Light, Run Dry Tee, Run Warm Tee, Run Dry Short, Running Belt, Running Socks 3-Pack, Running Cap\nDOMYOS (FITNESS): 500 Fitness Tee, 120 Fitness Legging, 100 Fitness Mat, 500 Weight Training Glove, 900 Fitness Short, Cross Training Shoe, Resistance Band Set, Kettlebell 8kg, Dumbbell 5kg Pair, Gym Bag 20L\nKIPSTA (TEAM SPORTS): F100 Football Size 5, F500 Football Boot, F100 Shin Guard, Basketball R500, Handball H500, Volleyball V100, Rugby Ball R100, Football Jersey, Football Short\nNABAIJI (SWIMMING): Swim Short Classic, Swim Goggles 100, Kickboard, Swimsuit One-Piece, Swimming Cap, Fins, Pull Buoy\nB\'TWIN (CYCLING): Riverside 120 Bike, Triban RC120, Cycling Short Padded, Cycling Jersey, Cycling Gloves, Bike Lock, Bike Pump, Cycling Helmet\nARTENGO (RACKET): TR130 Tennis Racket, TB530 Tennis Ball, Badminton Racket Set, Padel Racket\nFORCLAZ (TREKKING): Trek 100 Tent, Trek 500 Sleeping Bag, MT500 Backpack 50L, Trek 100 Down Jacket, Merino Tee, Trekking Sock' },
  { id: 38, cat: '⚽ Sports & Activewear', tier: '🛒 Affordable', name: 'Puma', mall: 'Dubai Mall / MoE', location: 'Ground Floor', spec: 'Sports shoes, casual, motorsport, football', products: 'SHOES: Suede Classic XXI, Suede Mayu, RS-X, RS-X3, Cali Star, Cali Dream, Mayze, CA Pro Classic, Palermo, Speedcat OG, Ferrari Speedcat, BMW Motorsport Sneaker, Rider FV, Softride, Electrify Nitro 3, Deviate Nitro 3, Velocity Nitro 3, ForeverRun Nitro, Fuse 3.0, Flyer Runner, Slide Leadcat 2.0, Slide Royalcat\nAPPAREL MEN: Essentials Logo Tee, Essentials Logo Hoodie, Essentials Logo Jogger, Essentials+ Tape Tee, Power Full-Zip Hoodie, T7 Iconic Track Jacket, T7 Track Pant, BMW M Motorsport Tee, BMW M Motorsport Jacket, Scuderia Ferrari Polo, SF Race Tee, Teamliga Jersey, Swim Short, Training Tee, Training Short\nAPPAREL WOMEN: Essentials Logo Tee, Essentials Hoodie Crop, Essentials Legging, Essentials Bra, Run Favourite Tee, Run Favourite Tight, Fit Training Bra, Fit Training Tight, Classics Ribbed Tee, Classics Cropped Hoodie, T7 Track Jacket\nKIDS: Smash V2 Kids, Caven 2.0 Kids, Fun Racer Kids, Essentials Tee Kids, Essentials Hoodie Kids\nACCESSORIES: Phase Backpack, Challenger Duffel, Fundamentals Cap, BMW Motorsport Cap, Sock 3-Pack' },
  { id: 39, cat: '⚽ Sports & Activewear', tier: '🛒 Affordable', name: 'Skechers', mall: 'Various (10+)', location: 'Multiple malls', spec: 'Comfort footwear, walking, running, casual, kids', products: 'MEN: Go Walk 7 Lace-Up, Go Walk Arch Fit Iconic, Go Walk Max Effort, Go Walk 6 Slip-In, D\'Lites Hyper Burst, Skech-Air Dynamight, Arch Fit Infinity Cool, Max Cushioning Elite, Max Cushioning Arch Fit, Equalizer 5.0, Track Scloric, Track Knockhill, Energy Racer, Summits Brisbane, Uno Stand On Air, Sport Court 92, Relaxed Fit Respected, Slip-ins Ultra Flex 3.0, Go Run Consistent, Go Run Trail Altitude\nWOMEN: Go Walk Joy, Go Walk Arch Fit Grateful, D\'Lites Fresh Start, D\'Lites Bright Blossoms, Skech-Air Dynamight Luminosity, Arch Fit Big Appeal, Max Cushioning Elite, Uno Stand On Air, Ultra Flex 3.0, Summits Cool Classic, Street Uno Lite, Bobs Squad Chaos, Flex Appeal 4.0, Slip-ins Max Cushioning Smooth, Go Walk 7 Slip-in\nKIDS: S-Lights Galaxy, S-Lights Twisty Brights, Microspec Max, Comfy Flex, Go Run 600, Dreamy Dancer, Dynamight Ultra Torque\nSANDALS: Go Walk Flex Sandal, On-the-Go Arch Fit, Foamies, Cali Breeze, Go Walk Arch Fit Sandal\nWORK: Sure Track, Flex Advantage, Work Relaxed Fit, Squad SR' },
  // SOUVENIRS & GIFTS
  { id: 40, cat: '🎁 Souvenirs & Gifts', tier: '💎 High-End', name: 'Amouage', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Omani luxury fragrance house', products: 'Amouage — Bags, clothing, shoes, accessories (excluding watches, jewellery, perfumes)' },
  { id: 41, cat: '🎁 Souvenirs & Gifts', tier: '💎 High-End', name: 'Arabian Oud', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Arabian attars, oils, home fragrance', products: 'HOME: Oud Burner Electric, Oud Burner Traditional, Car Freshener, Mabkhara (incense holder)\nGIFT SETS: Oud Collection Gift Set, Kalemat Gift Set, Discovery Set 6-Piece, Travel Atomizer Set' },
  { id: 42, cat: '🎁 Souvenirs & Gifts', tier: '🏷️ Mid-Range', name: 'Bateel', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Premium Arabian dates, chocolates, gourmet, gifts', products: 'DATES: Khidri Dates Plain, Khidri Dates Almond Stuffed, Khidri Dates Candied Orange, Segai Dates Plain, Segai Dates Cream Cheese, Segai Dates Pistachio, Medjool Dates Plain, Medjool Dates Truffle, Medjool Dates Hazelnut Praline, Medjool Dates Dark Chocolate, Kholas Dates, Lulu Dates, Sokari Dates, Barhi Fresh Dates (seasonal), Ajwa Dates Premium\nCHOCOLATE: Chocolate Covered Dates Box, Gourmet Chocolate Bar Dark 70%, Gourmet Chocolate Bar Milk, Chocolate Truffle Selection, Date Chocolate Assorted Box, Chocolate Macadamia Bar, White Chocolate Date, Caramelized Almond Chocolate\nGOURMET: Organic Balsamic Vinegar, Date Molasses, Date Spread, Extra Virgin Olive Oil, Honey Raw Sidr, Honey Manuka, Date Coffee, Arabic Coffee Blend, Saffron Threads, Spice Gift Set\nGIFT BOXES: Bateel Gift Hamper Gold, Bateel Gift Hamper Silver, Bateel Gift Hamper Bronze, Date & Nut Collection Box, Ramadan Gift Box, Eid Gift Box, Wedding Favour Box, Corporate Gift Box Custom, Bateel Tin Box, Leather Box Premium' },
  { id: 43, cat: '🎁 Souvenirs & Gifts', tier: '🏷️ Mid-Range', name: 'Jo Malone', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'British luxury bath, body, home gifts', products: 'HOME: Home Candle 200g (all scents), Luxury Candle 2.5kg (select scents), Scented Diffuser, Pillow Mist, Discovery Set, Body Care Set, Miniature Set, Wedding Favours, Engraving Service' },
  { id: 44, cat: '🎁 Souvenirs & Gifts', tier: '🏷️ Mid-Range', name: 'Rituals', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Dutch body care, home, wellness, gifts', products: 'HOME: Fragrance Sticks (all collections), Mini Candle, XL Candle, Wardrobe Sachet, Gift Set Medium, Gift Set Large (Full Collection), Advent Calendar, Travel Set, Men Gift Set' },
  { id: 45, cat: '🎁 Souvenirs & Gifts', tier: '🛒 Affordable', name: 'Dubai Duty Free', mall: 'Dubai Airport DXB', location: 'T1, T2, T3', spec: 'Souvenirs, chocolates, gold, electronics, gifts', products: 'SOUVENIRS: Dubai Snow Globe, I Love Dubai Fridge Magnet Set, Camel Plush Toy Small, Camel Plush Toy Large, I Love Dubai Tee, Dubai Skyline Tee, UAE Flag Tee, Dubai Keychain Metal, Dubai Keychain Burj Khalifa, Dubai Postcard Set 10pc, Dubai Coffee Mug, Burj Al Arab Ornament, Dubai Skyline Ornament, Arabic Coffee Cup Set, Arabic Tea Glass Set, Camel Milk Chocolate Bar, Camel Milk Chocolate Box, Dates Gift Box DDF, Date Chocolate Assorted, Saffron Gift Box, Arabic Sweets Box, Dubai Map Poster, Sand Bottle Art, Arabic Calligraphy Print, Evil Eye Keychain, Gold Souk Keychain, Palm Jumeirah Model, Burj Khalifa Model Small\nCHOCOLATES: Godiva Box, Lindt Selection, Toblerone Large, Patchi Box, Bateel Box\nGOLD: 1g Gold Bar, Gold Coin' },
  { id: 46, cat: '🎁 Souvenirs & Gifts', tier: '🛒 Affordable', name: 'Miniso', mall: 'Various (10+)', location: 'Multiple malls', spec: 'Japanese-inspired budget gifts, toys, accessories', products: 'PLUSH: We Bare Bears Plush, Sanrio Character Plush, Disney Character Plush, Animal Plush (various sizes), Blind Box Figure, Collectible Figure Set\nTECH: Wireless Earphones, Wired Earphones, Phone Case (various models), Phone Stand, Power Bank, USB Cable, Portable Speaker, Desk Lamp LED\nHOME: Water Bottle 500ml, Water Bottle 1L, Storage Box, Organiser Basket, Cushion, Blanket Small, Photo Frame, Wall Clock, Mug, Tumbler\nSTATIONERY: Notebook A5, Notebook Set, Gel Pen Set, Highlighter Set, Pencil Case, Sticker Set, Washi Tape, Desk Organiser\nBAGS: Canvas Tote Bag, Drawstring Bag, Mini Backpack, Crossbody Small, Cosmetic Pouch, Travel Organiser\nTOYS: Building Block Mini Set, RC Car Mini, Board Game Mini, Card Game, Puzzle 300pc, Craft Kit Kids' },
  // TOYS & KIDS
  { id: 47, cat: '🧸 Toys & Kids', tier: '💎 High-End', name: 'LEGO Store (Flagship)', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Premium LEGO sets, exclusives, Pick-a-Brick', products: 'LEGO ARCHITECTURE: Burj Khalifa 21055, Eiffel Tower 10307, Statue of Liberty 21042, Great Pyramid of Giza 21058, Taj Mahal, Singapore Skyline, Tokyo Skyline, Dubai Skyline, New York City, Paris, London\nLEGO TECHNIC: Lamborghini Sián 42115, Ferrari Daytona SP3 42143, McLaren F1 42141, Porsche 911 GT3 RS, Land Rover Defender, Liebherr Crawler Crane, Ducati Panigale, Cat D11 Bulldozer, Mercedes-AMG F1\nLEGO STAR WARS: UCS Millennium Falcon 75192, UCS AT-AT, UCS Star Destroyer, UCS Republic Gunship, Razor Crest, X-Wing Starfighter, TIE Fighter, R2-D2, Darth Vader Helmet, Luke Skywalker Helmet, Clone Trooper Pack, AT-TE Walker\nLEGO ICONS: Eiffel Tower 10307, Orchid 10311, Flower Bouquet 10280, Succulents 10309, Bonsai Tree 10281, Dried Flower Centerpiece, Wildflower Bouquet, Camp Nou Stadium, Santiago Bernabéu, Old Trafford, Titanic, Atari 2600, Typewriter\nLEGO CITY: Police Station 60316, Fire Station, Hospital, Airport, Construction, Mining, Deep Sea, Space\nLEGO FRIENDS: Heartlake City, Pet Centre, Shopping Mall, Beach House, Horse Show\nLEGO HARRY POTTER: Hogwarts Castle, Hogwarts Express, Diagon Alley, Hagrid\'s Hut, Quidditch Match\nLEGO MARVEL: Avengers Tower, Iron Man Helmet, Spider-Man, Hulkbuster, Infinity Gauntlet\nLEGO SPEED CHAMPIONS: Ferrari, Lamborghini, Porsche, McLaren, BMW, Aston Martin, Pagani\nLEGO ART: World Map, Andy Warhol, Iron Man, Hokusai' },
  { id: 48, cat: '🧸 Toys & Kids', tier: '🏷️ Mid-Range', name: 'Toys R Us', mall: 'Various (5+)', location: 'Dubai Mall, MoE, Mirdif', spec: 'All toys, games, outdoor, licensed, baby', products: 'DOLLS & FASHION: Barbie Dreamhouse, Barbie Fashionista (various), Barbie Career (Doctor, Chef, etc.), Ken Doll, LOL Surprise OMG, LOL Surprise Mini, Disney Princess Doll Set, Frozen Elsa Doll, Encanto Mirabel, Na Na Na Surprise, Baby Alive, Cry Babies\nACTION FIGURES: Marvel Legends Series, Spider-Man Figure, Batman Figure, Transformers Beast, Power Rangers, Star Wars Black Series, Jurassic World Dinosaur, Sonic the Hedgehog, Super Mario, Minecraft Figure, Fortnite Victory Royale\nVEHICLES: Hot Wheels Track Builder, Hot Wheels Monster Trucks, Hot Wheels 5-Pack, Hot Wheels City, Matchbox, Nerf Elite 2.0 Commander, Nerf Fortnite, Nerf Ultra, Nerf Modulus, Nerf Rival, Water Gun Super Soaker\nCREATIVE: Play-Doh Kitchen Creations, Play-Doh Super Color Pack 20, Play-Doh Fun Factory, Crayola 64 Crayons, Crayola Marker Set, Spirograph, Aqua Beads, Hama Beads, Kinetic Sand, Slime Kit\nGAMES: Monopoly Classic, Monopoly Junior, Uno Card Game, Scrabble, Jenga, Operation, Game of Life, Clue, Risk, Trivial Pursuit, Connect Four, Battleship, Trouble, Sorry, Rubik\'s Cube, Chess Set\nOUTDOOR: Bicycle (various sizes), Scooter, Skateboard, Roller Blades, Trampoline, Swing Set, Pool Float, Beach Set\nBABY: Fisher-Price Laugh & Learn, Fisher-Price Little People, VTech Baby, LeapFrog, Sophie la Girafe, Lamaze Toy, Skip Hop Activity, Tummy Time Mat' },
  // WEDDING & BRIDAL
  { id: 49, cat: '💒 Wedding & Bridal', tier: '💎 High-End', name: 'Elie Saab Bridal', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Lebanese couture bridal, embellished gowns, veils', products: 'BRIDAL GOWNS: ES Haute Couture Ball Gown, ES Illusion Neckline A-Line, ES Cape Bridal Gown, ES Embellished Tulle Sheath, ES Lace Cathedral Train Mermaid, ES Off-Shoulder Mermaid, ES Beaded Bodice A-Line, ES Plunging V-Neck Column, ES High Neck Long Sleeve, ES Strapless Sweetheart, ES Fit-and-Flare Lace, ES Short Cocktail Bridal, ES Detachable Overskirt Gown, ES Feathered Hem Gown\nVEILS: Cathedral Veil Embroidered, Chapel Veil Lace, Fingertip Veil, Blusher Veil, Mantilla Veil Lace\nEVENING: ES Reception Dress Short, ES Evening Gown Long, ES Cocktail Dress\nACCESSORIES: Bridal Headpiece, Crystal Hair Comb, Bridal Belt' },
  { id: 50, cat: '💒 Wedding & Bridal', tier: '💎 High-End', name: 'Vera Wang', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Iconic bridal couture, gowns, veils, bridesmaids, accessories', products: 'BRIDAL GOWNS: Vera Wang Custom A-Line Gown, VW Custom Ball Gown, VW Custom Mermaid Gown, VW Custom Sheath Gown, VW Custom Fit-and-Flare, VW Custom Column Gown, VW Strapless Ball Gown, VW Off-Shoulder Gown, VW Illusion Neckline, VW V-Neck Gown, VW High Neck Gown, VW Long Sleeve Gown, VW Cap Sleeve, VW Halter Gown, VW Plunging Neckline, VW Backless Gown, VW Cathedral Train Gown, VW Chapel Train, VW Court Train, VW Detachable Train, VW Lace Appliqué Gown, VW Embroidered Tulle, VW Satin Gown, VW Crepe Gown, VW Organza Gown, VW Mikado Gown\nVEILS: Cathedral Veil (3m+), Chapel Veil (2.5m), Fingertip Veil, Elbow Veil, Blusher Veil, Birdcage Veil, Mantilla Veil, Lace Trim Veil, Crystal Edge Veil, Raw Edge Veil, Two-Tier Veil\nBRIDESMAIDS: VW Bridesmaid Long Dress, VW Bridesmaid Short Dress, VW Bridesmaid V-Neck, VW Bridesmaid Halter, VW Bridesmaid One-Shoulder, VW Bridesmaid Strapless, VW Junior Bridesmaid Dress, VW Flower Girl Dress\nACCESSORIES: Bridal Belt Crystal, Bridal Sash Embellished, Hair Comb Crystal, Hair Vine Pearl, Garter Set, VW Bridal Platform, VW Bridal Flat, VW Bridal Block Heel, VW Bridal Sandal' },
  { id: 51, cat: '💒 Wedding & Bridal', tier: '🏷️ Mid-Range', name: 'Damas (Bridal)', mall: 'Various (20+)', location: 'Multiple malls', spec: 'Wedding gold, diamond, bridal sets', products: 'BRIDAL SETS: Bridal Gold Choker Set, Kundan Bridal Set, Polki Bridal Set, Meenakari Bridal Set, Temple Jewellery Bridal\nBANGLES: Gold Bangle Set 4pc, Gold Bangle Set 6pc, Gold Bangle Set 8pc, Kangan Set, Stone-Studded Bangle Set, Diamond Cut Bangle\nOTHER BRIDAL: Maang Tikka Gold, Haath Phool (Hand Chain), Bridal Anklet Pair, Mangalsutra Diamond, Mangalsutra Gold, Kamar Bandh (Waist Chain), Wedding Band Platinum, Tie Pin Gold' },
  { id: 52, cat: '💒 Wedding & Bridal', tier: '🏷️ Mid-Range', name: 'Pronovias', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Spanish bridal, gowns, cocktail, accessories', products: 'BRIDAL: A-Line Gown (30+ styles), Mermaid Gown (25+ styles), Ball Gown (20+ styles), Sheath Dress (15+ styles), Fit & Flare (20+ styles), Princess Gown, Empire Waist, Tea Length, Mini Bridal, Detachable Sleeve, Detachable Overskirt, Removable Train\nFABRICS: Lace Gown, Tulle Gown, Crepe Gown, Satin Gown, Mikado Gown, Organza Gown, Chiffon Gown\nNECKLINES: V-Neck, Sweetheart, Off-Shoulder, Illusion, Bateau, Halter, Strapless, Plunging\nVEILS: Cathedral Veil, Chapel Veil, Fingertip Veil, Blusher, Hair Comb, Bridal Belt, Cocktail Dress Midi, Evening Gown, Mother of the Bride\nPLUS SIZE: Pronovias Plus Size Bridal (A-Line, Mermaid, Ball Gown styles)' },
  { id: 53, cat: '💒 Wedding & Bridal', tier: '🛒 Affordable', name: 'Meena Bazaar (Bridal)', mall: 'Bur Dubai', location: 'Textile Souk area', spec: 'Bridal fabrics, sarees, lehengas, custom tailoring', products: 'SAREES: Bridal Banarasi Silk Saree, Bridal Kanjivaram Silk Saree, Bridal Pattu Saree, Wedding Chiffon Saree, Bridal Georgette Saree, Bridal Net Saree, Bridal Organza Saree, Sequin Work Saree, Zari Work Saree, Stone Work Saree, Cut Dana Saree, Kashmiri Embroidered Saree\nLEHENGA: Lehenga Fabric Set (Skirt+Blouse+Dupatta), Heavy Embroidered Lehenga, Bridal Red Lehenga, Bridal Pink Lehenga, Bridal Maroon Lehenga, Velvet Lehenga, Net Lehenga, Georgette Lehenga, Raw Silk Lehenga, A-Line Lehenga, Circular Lehenga\nSUITS: Wedding Anarkali Suit, Bridal Sharara Set, Bridal Gharara Set, Salwar Kameez Bridal, Floor Length Anarkali, Palazzo Suit Bridal\nFABRICS: Bridal Zardozi Fabric Per Meter, Gold Thread Embroidered, Sequin Fabric, Net Fabric for Veil, Dupion Silk, Raw Silk, Velvet Fabric, Chiffon Fabric, Georgette Fabric, Organza Fabric, Brocade Fabric\nCUSTOM TAILORING: Bridal Blouse Custom Stitch, Bridal Lehenga Custom Stitch, Bridal Saree Blouse Stitch, Bridal Sharara Custom, Dupatta Finishing, Fall & Pico on Saree, Blouse Alteration, Heavy Embroidery Custom' },
  // BABY WEAR & KIDS APPAREL
  { id: 54, cat: '👶 Baby Wear & Kids', tier: '💎 High-End', name: 'Baby Dior', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Luxury baby & children\'s clothing, shoes, accessories', products: 'BABY (0-24 months): Baby Dior Romper Cotton, Baby Dior Romper Interlock, CD Logo Bodysuit Set 3-Pack, CD Logo Bodysuit Single, Baby Dior Cashmere Cardigan, Baby Dior Cashmere Booties, Baby Dior Fleece Snowsuit, Baby Dior Padded Jacket, Baby Dior Jogger Set (Top+Bottom), Baby Dior Dress Tulle, Baby Dior Bib Set 3-Pack, Baby Dior Bib Set Embroidered, CD Logo Baby Hat, Baby Dior Beanie, Baby Dior Blanket Cashmere, Baby Dior Blanket Cotton, Dior Oblique Stroller Blanket, Baby Dior Rattle, Baby Dior Comforter, Baby Dior Soft Toy\nKIDS (2-12 years): Dior Kids Logo Tee, Dior Kids Oblique Tee, Dior Kids Polo, Dior Kids Hoodie, Dior Kids Sweatshirt, Dior Kids Sweater Knit, Dior Kids Denim Jacket, Dior Kids Down Jacket, Dior Kids Puffer, Dior Kids Dress Oblique, Dior Kids Tulle Skirt, Dior Kids Tutu, Dior Kids Bermuda Short, Dior Kids Jogger, Dior Kids Legging, Dior Kids Sneaker Walk\'n\'Dior, Dior Kids Sneaker B23, Dior Kids Sandal, CD Logo Kids Cap, Dior Kids Backpack Oblique, Dior Kids Swimsuit\nGIFT SETS: Baby Dior Gift Set (Romper+Hat+Bib), Baby Dior Gift Set (Bodysuit 3-Pack+Bib), Newborn Gift Box (Blanket+Romper+Hat)' },
  { id: 55, cat: '👶 Baby Wear & Kids', tier: '💎 High-End', name: 'Gucci Kids', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Designer children\'s clothing, GG canvas, shoes', products: 'BABY (0-24m): GG Canvas Baby Shoe, GG Baby Sneaker, Baby Romper GG Print, Baby Romper Solid, GG Baby Hat, Baby Bib Set, GG Baby Blanket, GG Supreme Diaper Bag, Baby Bodysuit Logo, Baby Cardigan Knit, Baby Jogger Set, Baby Down Jacket, Baby Snowsuit\nKIDS (2-12y): GG Kids Logo Tee, GG Web Stripe Polo Kids, Kids GG Jacquard Sweater, Kids GG Hoodie, Kids GG Tracksuit, Kids GG Denim Jacket, Gucci Kids Dress Flora Print, Kids GG Pleated Skirt, Kids GG Jogger, Kids GG Short, GG Canvas Backpack Kids, Kids GG Supreme Slide, GG Kids Sneaker Ace, GG Kids Sneaker Screener, Kids GG Cap, Kids GG Swimsuit\nTEEN: GG Logo Teen Tee, Teen GG Hoodie, Teen GG Jean, Teen GG Sneaker, Teen GG Jacket' },
  { id: 56, cat: '👶 Baby Wear & Kids', tier: '🏷️ Mid-Range', name: 'Mamas & Papas', mall: 'Various', location: 'Multiple malls', spec: 'UK baby brand, nursery, clothing, gear, gifts', products: 'CLOTHING BABY: Welcome to the World Bodysuit Set 5pc, Knitted Romper, Embroidered Sleepsuit, First Size Sleepsuit 3-Pack, Essentials Bodysuit 5-Pack, Dungaree Set, Dress & Tights Set, Jogger Set (Top+Bottom), Cardigan Knit, Jacket Quilted, Snowsuit Pramsuit, Swimsuit, Sun Hat, Scratch Mittens, Sock Set 3-Pack\nCLOTHING TODDLER: Jersey Dress, Denim Dungaree, Polo Shirt, Stripe Tee, Jogger Pant, Raincoat, Puffer Jacket, Legging 2-Pack, Graphic Sweatshirt\nBEDDING: Cellular Blanket, Knitted Blanket, Muslin Swaddle 3-Pack, Sleeping Bag 1.0 Tog, Sleeping Bag 2.5 Tog, Fitted Sheet Set, Cot Bed Duvet Set, Moses Basket Sheet Set\nNURSERY: Cot Bed, Mattress, Changing Unit, Wardrobe, Shelf, Night Light, Musical Mobile, Nursery Set Bundle\nTRAVEL: Pushchair, Stroller, Car Seat Group 0+, Car Seat Group 1, ISOFIX Base, Travel Cot, Carrier, Changing Bag, Pram Organizer, Parasol, Rain Cover, Footmuff\nFEEDING: Bottle Set, Steriliser, Breast Pump, Highchair, Weaning Set, Bib Set 3-Pack, Sippy Cup, Snack Pot, Plate & Cutlery Set\nBATHTIME: Baby Bath, Bath Support, Hooded Towel, Wash Mitt Set, Top & Tail Bowl, Thermometer\nGIFTS: Newborn Gift Hamper, Milestone Card Set, Baby Record Book, Comforter Toy, First Teddy, Photo Frame' },
  { id: 57, cat: '👶 Baby Wear & Kids', tier: '🏷️ Mid-Range', name: 'Tommy Hilfiger Kids', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Preppy children\'s fashion, sportswear', products: 'BABY (0-24m): TH Baby Bodysuit 3-Pack, TH Baby Romper, TH Baby Jogger Set, TH Baby Gift Set (Bodysuit+Hat+Bib), TH Baby Puffer Jacket, TH Baby Shoe Velcro, TH Baby Hat\nKIDS (2-8y): TH Flag Logo Tee Kids, TH Essential Polo Kids, TH Essential Hoodie Kids, TH Logo Sweatshirt Kids, TH Denim Short Kids, TH Jogger Pant Kids, TH Puffer Jacket Kids, TH Denim Jacket Kids, TH Velcro Sneaker Kids, TH Swimsuit Kids, TH Cap Kids, TH Backpack Kids\nTEEN (8-16y): TH Polo Teen, TH Hoodie Teen, TH Jean Teen, TH Varsity Jacket Teen, TH Sneaker Teen, TH Swim Short Teen' },
  { id: 58, cat: '👶 Baby Wear & Kids', tier: '🛒 Affordable', name: "Carter's", mall: 'Various', location: 'Multiple malls, online', spec: 'American kids basics, baby essentials', products: 'BABY (0-24m): Bodysuit 5-Pack (various prints), Short Sleeve Bodysuit 5-Pack, Long Sleeve Bodysuit 5-Pack, Sleep & Play Footed 3-Pack, Zip-Up Sleep & Play, Snap-Up Cotton Sleep & Play, Romper Set (Top+Short), Side-Snap Tee Set, Character Bodysuit, Organic Cotton Bodysuit, Cardigan, Pant 4-Pack, Sock 6-Pack, Bib 4-Pack, Hat Set, Mittens, Blanket\nTODDLER (2-5y): Graphic Tee, Character Tee, Polo Shirt, Oxford Shirt, Hoodie, Jogger, Denim, Short, Dress, Legging, Rashguard Swim Set, Pyjama 4-Pack Snug Fit, Fleece Pullover, Rain Jacket\nKIDS (5-12y): Graphic Tee, Logo Hoodie, Jean, Jogger, Short, Polo, Active Set, Snowsuit, Pyjama Set, Uniform Polo, Uniform Pant\nESSENTIALS: Hospital Coming Home Set, First Doll, Lovey Blanket, Security Blanket, Changing Pad Cover, Crib Sheet, Swaddle Blanket 4-Pack' },
  { id: 59, cat: '👶 Baby Wear & Kids', tier: '🛒 Affordable', name: 'Mothercare', mall: 'Various (10+)', location: 'Multiple malls', spec: 'Baby & kids clothing, maternity, nursery, toys', products: 'BABY CLOTHING: Pure Cotton Bodysuit 5-Pack, Bodysuit 7-Pack, Short Sleeve Bodysuit 5-Pack, Sleepsuit 3-Pack, Sleepsuit Zip 3-Pack, Sleepsuit 5-Pack, My First Outfit (Bodysuit+Legging+Hat), Dungaree & Bodysuit Set, Dress & Tights Set, Romper 3-Pack, Jogger Set, Cardigan Knit, Jacket Padded, Snowsuit, All-in-One, Sock 5-Pack, Hat & Mitt Set, Bib 5-Pack, Scratch Mitt 3-Pack, Muslin Cloth 6-Pack\nKIDS CLOTHING: Graphic Tee, Polo Shirt, Hooded Sweatshirt, Jogger Pant, Jean Straight, Legging 2-Pack, Dress Jersey, Skirt Denim, Shorts, Raincoat, Puffer Jacket, School Uniform Polo, School Trouser\nMATERNITY: Maternity Legging, Maternity Jean, Maternity Dress, Maternity Top, Nursing Bra, Nursing Vest, Maternity Bump Band, Maternity Coat\nNURSERY: Cot Bed, Mattress Foam, Mattress Sprung, Fitted Sheet 2-Pack, Cellular Blanket, Sleeping Bag 0.5 Tog, Sleeping Bag 1.0 Tog, Sleeping Bag 2.5 Tog, Blackout Blind, Mobile Musical, Moses Basket' },
  // LINGERIE
  { id: 60, cat: '🩱 Lingerie & Intimate Wear', tier: '💎 High-End', name: 'Agent Provocateur', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Luxury provocative lingerie, bridal, accessories', products: 'BRAS: Lorna Plunge Bra, Lorna Full Cup Bra, Mercy Corset Bra, Lucky Full Cup, Lucky Plunge, Rosalind Plunge, Rosalind Full Cup, Oona Bra, Zadi Bra, Luna Bralette, Eden Balconette, Helene Underwired, Whitney Plunge\nBOTTOMS: Lorna Thong, Lorna Brief, Mercy Thong, Lucky Thong, Lucky Brief, Rosalind Thong, Rosalind Brief, Oona Brief, Zadi Brief, Eden Brazilian, Whitney Thong, Luna Thong\nBODIES & CORSETS: Mercy Corset, Lorna Bodysuit, Lucky Bodysuit, Rosalind Body, Zadi Body, Fatale Basque, Whitney Playsuit\nBRIDAL: Bridal White Bra Set (Plunge+Thong), Bridal Bodysuit White, Bridal Corset White, Bridal Suspender White, Bridal Robe Silk White, Bridal Garter\nSLEEPWEAR: AP Silk Kimono Long, AP Silk Kimono Short, Silk Robe, Silk Chemise, Silk Pyjama Set, Silk Eye Mask\nSWIMWEAR: Bikini Top, Bikini Bottom, One-Piece, Sarong' },
  { id: 61, cat: '🩱 Lingerie & Intimate Wear', tier: '💎 High-End', name: 'La Perla', mall: 'Dubai Mall', location: 'Fashion Avenue', spec: 'Italian luxury lingerie, silk, bridal, beachwear', products: 'BRAS: Maison Contouring Bra, Maison Padded Bra, Maison Underwired Bra, Maison Strapless Bra, Soutache Triangle Bra, Soutache Underwired Bra, Soutache Bandeau, Lace Triangle Bra, Lace Balconette, Lace Plunge Bra, Silk Bralette, Tulle Triangle Bra, Sport Bra Lace\nBOTTOMS: Maison Full Brief, Maison Thong, Maison Brazilian, Soutache Thong, Soutache Brief, Soutache Shorty, Lace Brazilian Brief, Lace Thong, Lace High-Waist Brief, Silk Brief, Tulle Thong\nBODIES: Soutache Bodysuit, Lace Bodysuit, Tulle Bodysuit, Silk Bodysuit, Corset Soutache, Bustier Lace\nSLEEPWEAR: Silk Short Pyjama Set, Silk Long Pyjama Set, Silk Robe Long, Silk Robe Short, Silk Chemise Short, Silk Chemise Long, Silk Camisole & Short Set, Cotton Pyjama Set, Silk Sleep Mask, Cashmere Robe\nBRIDAL: Bridal White Bra Set, Bridal Bodysuit, Bridal Robe, Bridal Chemise, Bridal Suspender Belt, Bridal Garter, Bridal Thong, Bridal Stocking\nSWIMWEAR: Bikini Top Triangle, Bikini Top Bandeau, Bikini Bottom Classic, Bikini Bottom High-Waist, One-Piece Swimsuit, Sarong, Cover-Up Dress, Beach Kaftan\nLOUNGEWEAR: Silk Loungewear Top, Silk Loungewear Pant, Cashmere Loungewear, Jersey Loungewear Set' },
  { id: 62, cat: '🩱 Lingerie & Intimate Wear', tier: '🏷️ Mid-Range', name: 'Intimissimi', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Italian lingerie, loungewear, cashmere, silk', products: 'BRAS: Silk Satin Triangle Bra, Silk Satin Balconette, Lace Triangle Bralette, Lace Balconette Bra, Lace Push-Up Bra, Microfiber Bandeau, Microfiber Triangle, Cotton Bralette, Push-Up Bra Natural, Seamless Bra, Sports Bra Light, Strapless Bra\nBOTTOMS: Lace Brazilian Brief, Lace Thong, Lace Hipster, Cotton Brief 3-Pack, Microfiber Thong, Seamless Brazilian, Seamless Thong, Silk Brief, High-Waist Brief, Cotton Thong 3-Pack\nLOUNGEWEAR: Ultralight Modal Tee, Ultralight Modal Legging, Ultralight Tank, Cotton PJ Set, Satin PJ Set, Silk PJ Set Short, Silk PJ Set Long, Silk Kimono, Silk Slip Dress, Cotton Nightdress, Fleece Robe, Cotton Robe\nCASHMERE & SILK: Cashmere Blend V-Neck Top, Cashmere Blend Cardigan, Cashmere Blend Legging, Silk Satin Camisole, Silk Satin Shorts, Silk Slip, Ultralight Cashmere Pullover\nMEN: Cotton V-Neck Tee, Cotton Crew Tee, Cotton Boxer, Silk Boxer, Jersey Trunk, Cotton Brief, Pyjama Set Cotton' },
  { id: 63, cat: '🩱 Lingerie & Intimate Wear', tier: '🏷️ Mid-Range', name: 'Oysho', mall: 'Dubai Mall', location: 'Ground Floor', spec: 'Inditex lingerie, sleepwear, active, swim', products: 'LINGERIE: Cotton Bralette, Ribbed Seamless Bralette, Lace Triangle Bra, Lace Balconette, Padded Bra Cotton, Push-Up Bra, Seamless Brief 3-Pack, Cotton Brief 3-Pack, Lace Thong, Lace Brazilian, Cotton Thong 3-Pack, Seamless Thong, Cotton Boxer Short\nSLEEPWEAR: Satin Pyjama Set Short, Satin Pyjama Set Long, Cotton PJ Set, Jersey PJ Set, Ribbed PJ Set, Flannel PJ Set, Nightdress Cotton, Nightdress Satin, Fluffy Robe, Cotton Robe, Satin Robe, Slippers Fluffy, Sleep Mask\nACTIVEWEAR: Seamless Sports Bra, High Support Sports Bra, Medium Support Bra, Ribbed Legging, Seamless Legging, Training Legging, Gym Crop Top, Training Tee, Running Tight, Yoga Tight, Biker Short, Training Hoodie, Windbreaker\nSWIMWEAR: Bikini Top Triangle, Bikini Top Bandeau, Bikini Top Crop, Bikini Bottom Classic, Bikini Bottom High-Waist, Bikini Bottom Brazilian, One-Piece Swimsuit, Surf Suit, Cover-Up Shirt, Sarong\nACCESSORIES: Yoga Mat, Resistance Band, Sports Bag, Water Bottle, Scrunchie Set, Hair Band' },
  { id: 64, cat: '🩱 Lingerie & Intimate Wear', tier: '🏷️ Mid-Range', name: "Victoria's Secret", mall: 'Dubai Mall', location: 'Ground Floor (2 levels)', spec: 'Global lingerie, PINK line', products: 'BRAS: T-Shirt Lightly Lined Demi, T-Shirt Full Coverage, VS Push-Up Bra, VS Bombshell Add-2-Cups Push-Up, VS So Obsessed Push-Up, Unlined Full-Cup Lace, Unlined Plunge Lace, Body by Victoria Lined Demi, Body by Victoria Perfect Shape, Strapless Multiway, Wireless Bra, Bralette Lace Triangle, Bralette Ribbed Cotton, VS Sport Bra Light Support, VS Sport Bra Medium Support, VS Sport Bra Maximum Support, Nursing Bra, Maternity Bra, Balconette Bra, Longline Bra\nBOTTOMS: Thong Lace (all colours), Thong Cotton (all colours), Bikini Brief Cotton 5-Pack, Bikini Lace, Brazilian Lace, Brazilian Cotton, Cheeky Lace, Cheeky Cotton, Hipster, Boyshort, Hiphugger, Seamless Thong, Seamless Bikini, No-Show Thong, Period Brief, High-Waist Shaping\nPINK LINE: PINK Logo Hoodie, PINK Logo Tee, PINK Campus Tee, PINK Oversized Tee, PINK Legging, PINK Jogger, PINK Shorts, PINK Sports Bra, PINK Cotton Bralette, PINK Cotton Bikini 5-Pack, PINK Cotton Thong 5-Pack, PINK Boyfriend Crew, PINK Crossbody Bag, PINK Backpack, PINK Water Bottle, PINK Blanket\nSLEEPWEAR: Satin PJ Set Short Sleeve/Short, Satin PJ Set Long Sleeve/Long, Modal PJ Set, Cotton PJ Set, Flannel PJ Set, Satin Robe Short, Satin Robe Long, Satin Chemise, Slip Dress Satin, Sleep Mask Satin, Slippers Faux Fur\nLOUNGEWEAR: Cozy Knit Hoodie, Cozy Knit Jogger, Cozy Knit Short, Fleece Sweatshirt, Jersey Romper, Ribbed Tank' },
  { id: 65, cat: '🩱 Lingerie & Intimate Wear', tier: '🛒 Affordable', name: 'Marks & Spencer Lingerie', mall: 'Various', location: 'Multiple malls', spec: 'British reliable lingerie, basics, maternity', products: 'BRAS: Sumptuously Soft™ Non-Wired Bra, Sumptuously Soft™ Full Cup, Sumptuously Soft™ Plunge, Total Support Non-Wired Full Cup, Total Support Embroidered, Body Define™ Wired Bra, Body Define™ Non-Wired, Flexifit™ Non-Wired, Flexifit™ Full Cup, Cotton Rich Non-Wired, Cotton Rich Full Cup, Lace Non-Padded Full Cup, Strapless Multiway, T-Shirt Bra Non-Wired, T-Shirt Bra Full Cup, Sports Bra High Impact, Sports Bra Medium Impact, Maternity Non-Wired, Nursing Non-Wired, Post-Surgery Bra, First Bra Teens, Bralette Cotton, Bralette Lace\nBRIEFS: Cotton Rich Full Brief 5-Pack, Cotton Rich Bikini 5-Pack, Cotton Rich Thong 5-Pack, Cotton Rich High Leg 5-Pack, Lace Full Brief 3-Pack, No VPL Thong 3-Pack, No VPL Brazilian 3-Pack, Seamless High Leg 3-Pack, Modal Rich Brief 3-Pack, Cotton Hipster 5-Pack, Lace Bikini 3-Pack, Boy Short 3-Pack, Control Brief High Waist, Maternity Brief 3-Pack\nSHAPEWEAR: High Waist Shaping Brief, Thigh Slimmer, Waist Cincher, Full Slip Shaping, Light Control Brief, Medium Control Brief, Firm Control Brief, Bodyshaping Vest\nSLEEPWEAR: Sleep Jersey PJ Set, Sleep Cotton PJ Set, Sleep Satin Short PJ, Sleep Flannel PJ, Cotton Nightdress, Jersey Nightshirt, Satin Chemise, Dressing Gown Fleece, Dressing Gown Cotton, Sleep Shorts & Vest Set\nMEN: Pure Cotton Brief 5-Pack, Cotton Stretch Boxer 3-Pack, Cool & Fresh™ Trunk 3-Pack, Airflex™ Brief 3-Pack, Cotton Rich Vest 3-Pack, Thermal Vest, Thermal Long Johns, Jersey PJ Set, Cotton PJ Set, Dressing Gown Cotton\nSOCKS: Cotton Rich Sock 7-Pack Men, Cotton Rich Sock 5-Pack Women, Sports Sock 5-Pack, Thermal Sock 3-Pack, Trainer Liner 5-Pack, Tights 3-Pack, Tights 40 Denier 3-Pack, Tights 60 Denier 2-Pack, Hold-Ups 2-Pack' },
  { id: 66, cat: '🩱 Lingerie & Intimate Wear', tier: '🛒 Affordable', name: "Women'secret", mall: 'Dubai Mall / MoE', location: 'Ground Floor', spec: 'Inditex affordable lingerie, sleepwear, swim', products: 'BRAS: Cotton Bra Padded, Cotton Bra Non-Padded, Lace Bralette, Lace Plunge, Push-Up Bra, T-Shirt Bra, Strapless Bra, Sports Bra, Nursing Bra, Maternity Bra, Triangle Bra, Bandeau, Essential Bra\nBRIEFS: Cotton Brief 5-Pack, Cotton Bikini 3-Pack, Lace Thong 3-Pack, Lace Brazilian, Seamless Thong, Seamless Brief, High-Waist Shaping, Cotton Boxer, Cotton Hipster\nBODIES: Lace Bodysuit, Cotton Bodysuit, Seamless Bodysuit, Shapewear Bodysuit\nBRIDAL: Bridal White Bra Set, Bridal White Bodysuit, Bridal Thong White, Bridal Garter\nSLEEPWEAR: Satin PJ Set Short, Satin PJ Set Long, Cotton PJ Set, Jersey PJ Long, Flannel PJ Set, Nightdress Cotton, Nightdress Satin, Robe Fluffy, Robe Cotton, Slippers, Sleep Mask\nSWIMWEAR: Bikini Set, Bikini Top, Bikini Bottom, One-Piece, Tankini, Cover-Up\nACCESSORIES: Lingerie Bag, Gift Set (Bra+Brief), Multi-Pack Sets' },
];

const CATEGORIES = ['All', ...Array.from(new Set(BRANDS.map(b => b.cat)))];
const TIERS = ['All Tiers', '💎 High-End', '🏷️ Mid-Range', '🛒 Affordable'];

const TIER_COLORS = {
  '💎 High-End': 'bg-amber-50 text-amber-700 border-amber-200',
  '🏷️ Mid-Range': 'bg-blue-50 text-blue-700 border-blue-200',
  '🛒 Affordable': 'bg-green-50 text-green-700 border-green-200',
};

function BrandCard({ brand }) {
  const [open, setOpen] = useState(false);
  const sections = brand.products.split('\n').map(line => {
    const colonIdx = line.indexOf(':');
    if (colonIdx > 0 && colonIdx < 25) {
      return { heading: line.slice(0, colonIdx).trim(), items: line.slice(colonIdx + 1).trim() };
    }
    return { heading: null, items: line.trim() };
  }).filter(s => s.items);

  return (
    <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden hover:shadow-md transition-shadow">
      <button className="w-full text-left p-4 flex items-start justify-between gap-3" onClick={() => setOpen(!open)}>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <span className="font-bold text-sm text-gray-900">{brand.name}</span>
            <span className={`text-[10px] font-semibold border px-1.5 py-0.5 rounded-full ${TIER_COLORS[brand.tier] || 'bg-gray-100 text-gray-600 border-gray-200'}`}>{brand.tier}</span>
          </div>
          <p className="text-xs text-gray-500 leading-snug">{brand.spec}</p>
          <div className="flex items-center gap-3 mt-1.5 flex-wrap">
            <span className="flex items-center gap-1 text-[11px] text-gray-400"><MapPin className="w-3 h-3" />{brand.mall}</span>
            <span className="flex items-center gap-1 text-[11px] text-gray-400"><Tag className="w-3 h-3" />{brand.location}</span>
          </div>
        </div>
        <div className="shrink-0 mt-1">
          {open ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
        </div>
      </button>
      {open && (
        <div className="border-t border-gray-100 px-4 py-3 bg-gray-50">
          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2 flex items-center gap-1"><Package className="w-3 h-3" /> Product Catalog</p>
          <div className="space-y-2">
            {sections.map((s, i) => (
              <div key={i}>
                {s.heading && <p className="text-[10px] font-bold text-gray-600 uppercase tracking-wide mb-0.5">{s.heading}</p>}
                <p className="text-xs text-gray-600 leading-relaxed">{s.items}</p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default function BrandDirectory() {
  const [search, setSearch] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');
  const [activeTier, setActiveTier] = useState('All Tiers');

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return BRANDS.filter(b => {
      const matchesSearch = !q || b.name.toLowerCase().includes(q) || b.products.toLowerCase().includes(q) || b.spec.toLowerCase().includes(q);
      const matchesCat = activeCategory === 'All' || b.cat === activeCategory;
      const matchesTier = activeTier === 'All Tiers' || b.tier === activeTier;
      return matchesSearch && matchesCat && matchesTier;
    });
  }, [search, activeCategory, activeTier]);

  const groupedByCategory = useMemo(() => {
    const map = {};
    for (const b of filtered) {
      if (!map[b.cat]) map[b.cat] = [];
      map[b.cat].push(b);
    }
    return map;
  }, [filtered]);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 py-4">
          <div className="flex items-center gap-3 mb-3">
            <div className="w-8 h-8 rounded-xl bg-primary flex items-center justify-center shrink-0">
              <Package className="w-4 h-4 text-primary-foreground" />
            </div>
            <div>
              <p className="text-[10px] font-black text-foreground leading-none">SEND<span className="text-accent">IT</span>HOME</p>
              <p className="text-[9px] text-muted-foreground">Dubai Brand & Product Directory</p>
            </div>
          </div>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              value={search}
              onChange={e => setSearch(e.target.value)}
              placeholder="Search brands or products..."
              className="pl-9 h-9 bg-gray-50 text-sm"
            />
          </div>
          {/* Tier filter */}
          <div className="flex gap-1.5 mt-2 flex-wrap">
            {TIERS.map(t => (
              <button key={t} onClick={() => setActiveTier(t)}
                className={`text-[11px] font-semibold px-2.5 py-1 rounded-full border transition-colors ${activeTier === t ? 'bg-primary text-primary-foreground border-primary' : 'bg-white text-gray-600 border-gray-200 hover:bg-gray-50'}`}>
                {t}
              </button>
            ))}
          </div>
        </div>
        {/* Category tabs */}
        <div className="max-w-5xl mx-auto px-4 pb-0">
          <div className="flex gap-1 overflow-x-auto pb-0 scrollbar-hide">
            {CATEGORIES.map(c => (
              <button key={c} onClick={() => setActiveCategory(c)}
                className={`shrink-0 text-[11px] font-semibold px-3 py-2 border-b-2 transition-colors whitespace-nowrap ${activeCategory === c ? 'border-accent text-accent' : 'border-transparent text-gray-500 hover:text-gray-800'}`}>
                {c}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Stats bar */}
      <div className="max-w-5xl mx-auto px-4 py-3">
        <p className="text-xs text-gray-500">
          Showing <span className="font-semibold text-gray-800">{filtered.length}</span> brand{filtered.length !== 1 ? 's' : ''} 
          {search && <span> matching "<strong>{search}</strong>"</span>}
          {' '}· <span className="text-gray-400 text-[11px]">NO Watches · NO Jewellery · NO Perfumes · NO Furniture</span>
        </p>
      </div>

      {/* Brand list */}
      <div className="max-w-5xl mx-auto px-4 pb-12 space-y-8">
        {Object.entries(groupedByCategory).map(([cat, brands]) => (
          <div key={cat}>
            <h2 className="text-sm font-bold text-gray-700 mb-3 sticky top-[148px] bg-gray-50 py-1">{cat} <span className="font-normal text-gray-400">({brands.length})</span></h2>
            <div className="grid gap-2 sm:grid-cols-2">
              {brands.map(b => <BrandCard key={b.id} brand={b} />)}
            </div>
          </div>
        ))}
        {filtered.length === 0 && (
          <div className="text-center py-16">
            <Package className="w-10 h-10 text-gray-300 mx-auto mb-3" />
            <p className="text-sm text-gray-500">No brands found</p>
          </div>
        )}
      </div>

      {/* Footer */}
      <div className="bg-primary text-primary-foreground text-center py-4 px-4">
        <p className="text-xs font-bold">Send It Home — Dubai Complete Brand Directory</p>
        <p className="text-[10px] opacity-70 mt-0.5">66 brands · ~3,919 products · Powered by FedEx & DHL</p>
      </div>
    </div>
  );
}